### ISSUE TITLE
Minor  changes

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#1]
Just a few minor changes:

1. In the source code let's change the 'run' folder to 'bin'.  I think this is more consistent with most software.
2. In between the console prompt (i.e. KINC:>) and where users type commands can we add a space?  This is similar to the bash console.
3. On Kamiak kinc takes a while to load. I assume it's because it's checking on the GPUs available.  Perhaps we should print out something to the screen immediately something like what R does--a bit of a textual "splash screen".  Some initial help text would be beneficial.  And maybe some text to let the user know why it's hanging a bit..  This way it doesn't seem like just stuck.

**Comment by 4ctrl-alt-del** [comment]
Only #1 applies to KINC... changed in commit 1c0f98c3ed55797b3173cd1dae33f9ecd0b71227
Other issues moved to ACE issue at https://github.com/SystemsGenetics/ACE/issues/20
