### ISSUE TITLE
Sample string in export

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#102]
The sample string, when exporting with KINC is a series of numbers.  This causes problems when importing the network into Cytoscape as Cytoscape interprets it as a huge integer and rewrites it.  I suggest we add a `CSS:` prefix  (for "cluster sample string") to it so that it does not get interpreted as a numeric value by any downstream analysis

**Comment by bentsherman** [comment]
@spficklin The extract analytic has a `--format minimal` option which will exclude the sample string from the output, that could be an easy way to extract a network file that is suitable for Cytoscape.

**Comment by spficklin** [comment]
Oh, but I want the sample string to show up in Cytoscape too.

**Comment by spficklin** [comment]
I'm closing this out. I don't think it's needed so much. With the new 3D viewer for KINC this isn't necessary.
