### ISSUE TITLE
Add GUI Customization

### ISSUE THREAD

**Issue by 4ctrl-alt-del** [SystemsGenetics/KINC#103]
KINC needs to add GUI branding with the new EAbstractCustomizer abstract singleton class implemented in the ACE gui library. This includes:
* Custom setup of the data menu
* Custom setup of the analytic menu
* Title and rich text body for an about dialog
* Splash screen pixmap
* Window icon

**Comment by bentsherman** [comment]
@4ctrl-alt-del could you add an example implementation of this to the ACE example program?

**Comment by 4ctrl-alt-del** [comment]
@bentsherman sorry the example is kind of hidden within the GUI library. Look at ace_defaultcustomizer.h/cpp as an example.

**Comment by bentsherman** [comment]
Done.
