### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#105]
I'm getting the following error when trying to compile the KINC using ACE 3.1.0:
```
../../src/core/similarity_opencl_worker.cpp: In member function ‘virtual std::unique_ptr<EAbstractAnalyticBlock> Similarity::OpenCL::Worker::execute(const EAbstractAnalyticBlock*)’:
../../src/core/similarity_opencl_worker.cpp:241:15: error: ‘class OpenCL::CommandQueue’ has no member named ‘wait’
       _queue->wait();
```
Any thoughts on a resolution?

**Comment by bentsherman** [comment]
@spficklin If you're using the master branch of KINC then you need to use the develop branch of ACE. That error looks like a feature that was implemented after ACE 3.1.0.

**Comment by spficklin** [comment]
@bentsherman I'm using ACE 3.1.0.  I'll switch to the master branch of ACE then. Thanks.

**Comment by bentsherman** [comment]
@spficklin Not the master branch, the develop branch. The master branch right now is just the same as 3.1.0. (This is what I was talking about in that email thread about the GEMmaker develop branch.)

**Comment by spficklin** [comment]
understood. Thanks for the correction.

**Comment by spficklin** [comment]
That worked. Thanks @bentsherman
