### ISSUE TITLE
Network Visualization Tool

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#107]
We need an easy-to-use Python or R tool that could easily draw a KINC condition-specific network.  This way folks who just want a quick peak, without having to load it up into Cytoscape can do so.  It would be preferrable if we can make the image publication quality for papers as well.

**Comment by biggstd** [comment]
I created a script in [this pull request](https://github.com/SystemsGenetics/KINC/pull/114). It is functional and looks ok. Let me know if any changes or options should be added.

**Comment by spficklin** [comment]
This is completed with PR #114
