### ISSUE TITLE
Bug in conditional testing due to ordering of samples

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#108]
If the samples in the annotation matrix don't match the order in the expression matrix then it can lead to false edges.  As per a conversation on Slack with @MitchsGreer.  The sample string for the edge is  used to map the conditions but there is a missing step to check the ordering.

**Comment by MitchsGreer** [comment]
Added support for out of order samples in the annotation matrix in commit e4a40ba0b7d4153110f79b11ead9ea36335f5aee. I also added a check for the correct sample size and sample names in commit 849b60480475873cecf4ce14053312ca426b139c.
