### ISSUE TITLE
Linear regression in conditional testing

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#109]
We have code partially complete to perform linear regression on conditions that are non categorical. We temporarily excluded that from the new `cscm-work` branch but it needs to be worked back in and a p-value calculated.

**Comment by MitchsGreer** [comment]
Added regression testing in commit e4a40ba0b7d4153110f79b11ead9ea36335f5aee and was later refined in commit 28a7250bf35f7aa2a32ba27249f7a2f88721fdf0, creating a p-value from the regression line.
