### ISSUE TITLE
Crashes with no GPU

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#11]
When I go to Settings > Set OpenCL Device, then KINC crashes with a core dump.  I'm assuming this is because I have no GPU in my VM.

**Comment by 4ctrl-alt-del** [comment]
That would be my guess yes I will see if I can replicate it on my machine
by disabling opencl. 
:)

Josh

**Comment by spficklin** [comment]
I no longer have this problem.  It seems to have been resolved with other changes.
