### ISSUE TITLE
--feat_type for the cond-test command corrupts the CSM file

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#117]
If I override the data type that KINC auto determines from the annotation matrix using the ``--feat_type`` argument then the output CSM file is corrupted and cannot be used to extract the network. If i don't provide the override it works okay.

**Comment by MitchsGreer** [comment]
Fixed overriding corruption and Quant/Ord test assignments in metadata in commit f040e3d683e9c28ac8c1851207e642137c395dcc.
