### ISSUE TITLE
KINC Version 3.4.0 -- not released, but mentioned in documentation as latest

### ISSUE THREAD

**Issue by SystemsGenetics-0310** [SystemsGenetics/KINC#123]
HI,

I would love to explore the condition specific functionality of kinc, as noted in version 3.4.0 in the newly updated documentation.  however, v3.3.0 seems to be the latest release here.  Any help on getting the updated version would be fantastic!

thanks for the great software!

**Comment by spficklin** [comment]
Hey @cugiuser sorry about the discrepancy.  We had planned to release 3.4.0 in December but got caught up in holidays and conferences.    We're doing some last minute checking and the updated release should be out hopefully in the next week.

**Comment by SystemsGenetics-0310** [comment]
Awesome Stephen.  Is it available now?

**Comment by spficklin** [comment]
@cugiuser Sorry for the delay on this. It's been a bit of a slow haul getting everything finished up.  We should be putting out the 3.4 version in the next few weeks or so as well as updated documentation.  Thanks for your patience.

**Comment by spficklin** [comment]
Hi @cugiuser.  We have not made the 3.4 release but we believe we've got all of the code changes needed for 3.4.  The online documentation now matches what is in the `master` branch of the code. So if you clone the code, compile (according to the instructions) you will effectively have version 3.4.  We should have that release in the next week or two.  But if you want to forge ahead. Please feel free.

**Comment by spficklin** [comment]
Oh, also... there's an example dataset now that comes with KINC that runs fairly quickly and the tutorial has been updated to use that example.  There are new filtering scripts and a 3D visualization script as well :-)  Although you have to install a few R and Python dependencies

**Comment by SystemsGenetics-0310** [comment]
Wonderful Dr. Ficklin.  Thank you so much for the note.  Will get busy with this today.

Take care,
Chris

**Comment by spficklin** [comment]
Okay v3.4 is now out!  Happy KINCing...

**Comment by SystemsGenetics-0310** [comment]
Awesome Stephen – I did clone the master branch from 3.3.0 – should I reinstall now with official 3.4.0?

All the best,
Chris

**Comment by spficklin** [comment]
If you cloned in the last 2 days you are fine.  We didn't make any changes.  If longer ago than that you should pull the official 3.4.0 version.

**Comment by spficklin** [comment]
@cugiuser we found a bug in the `cond-test` function for GEMs with samples greater than 31.  You'll want to upgrade to version 3.4.1 which was just released.

**Comment by SystemsGenetics-0310** [comment]
Thanks Stephen!

Take care,
chris

**Comment by spficklin** [comment]
@cugiuser release v3.4.2 is now out. It has a nice  3D visualization tool :-)

**Comment by SystemsGenetics-0310** [comment]
Awesome Stephen.  I hope you and your family are all well.  We are, just going stir crazy with all that’s going on.

Take care,
Chris
