### ISSUE TITLE
MPI problems for cond-test

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#133]
This analytic has a `_index` member variable that is meant to keep up with the current index while it's processing workblocks. I'm not sure it's actually working as expected in non MPI mode but  It's not appropriate to use that for MPI jobs.  We need to update the class so that it sets the starting indexes of each work block similar to the way  the corrpower was fixed in PR #126 .

**Comment by bentsherman** [comment]
I've found several issues with the conditional-test analytic that would definitely cause it to fail when using MPI. In fact I'm surprised it works even now. So I will be pushing some code changes soon that will allow conditional-test to work with MPI and resolve this issue.

**Comment by bentsherman** [comment]
@spficklin I just pushed some changes that should allow conditional-test to work. I don't have the necessary input data to test it but it should work for you, for single-core as well as MPI. If you could have somone test it and respond to this thread then I'll close this issue.

**Comment by spficklin** [comment]
Fixed. Thanks @bentsherman
