### ISSUE TITLE
Command-line usage text

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#14]
I'm wondering if it would be helpful to output help text if the user tries something like `KINC help`. The help text would list the command-line equivalents of each analytic. It would be a great way to show very quickly what all KINC can do from the command line, and it shouldn't be too hard to generate the commands from the analytics since it would use the same information used to generate the input forms. This goes also if the user tries `KINC run [...]` but provides invalid arguments; as far as I can tell, if that happens then KINC just starts up like nothing happened.

Now that I think about it, this could probably be implemented within the ACE framework. Something to think about.

**Comment by bentsherman** [comment]
In fact, it looks like the command-line functionality isn't there at all? It seems like even when I provide correct command-line arguments they are ignored. I'm guessing this feature hasn't been added yet.

**Comment by spficklin** [comment]
@4ctrl-alt-del and I have discussed this. We do need a command-line interface and it's on the TODO list.

**Comment by 4ctrl-alt-del** [comment]
The command line functionality is there you just have to compile to the correct library. ACE is composed of three shared libraries;

core
console
gui

When you compile the GUI version you link to gui/Application.h and compile with the core and gui libraries. When you compile the command line version you link to console/Application.h with the core and console libraries.

This way the command line version only requires the qtcore libraries to run. It would be very annoying if the command line version required a super computer server to have the full suite of Qt, a GUI library, to be installed on it. This is why I did it this way.

**Comment by 4ctrl-alt-del** [comment]
Also the develop branch of KINC is compiled as the GUI version by default.

**Comment by bentsherman** [comment]
Okay, I was able to build KINC with ACE console, so we do have the command-line interface. I haven't figured out yet how to use the interface, so I think the issue of usage text is still relevant here. Maybe just adding `KINC help [command]` in the ACE console library to show how to use each analytic.

**Comment by 4ctrl-alt-del** [comment]
That's what the GUI does. If you notice whenever you run a command the main GUI window has a text widget that outputs the command line version of any analytic you run.

**Comment by spficklin** [comment]
@4ctrl-alt-del and I have discussed auto-creating help text for the command-line so that you can type something like --help and it will print out the help text similar to what you get with the GUI.  That is on our schedule of things to get done...

**Comment by bentsherman** [comment]
@spficklin Sounds good.

@4ctrl-alt-del Yeah the GUI console is very helpful but it's hindered by the fact that you can't have the GUI interface and console interface in one build, so if you wanted to test a command, you would have to rebuild the application. I added some machinery to `KINC.pro` to make this process easier, but it would be beneficial to have both interfaces in one build. I think most users will expect to have both in one.

**Comment by 4ctrl-alt-del** [comment]
I suppose I could add the command line functionality to the GUI program so it has both if you think that would be helpful?

**Comment by bentsherman** [comment]
Yes I think that would be good.

**Comment by spficklin** [comment]
It would be nice to have a single binary that could do both a GUI and command-line.

**Comment by 4ctrl-alt-del** [comment]
I can do that Stephen. However, that would require any super computer server to have the full Qt suite installed on its system along with X windows to support it. In my experience most servers have no GUI components especially something as large as Qt.

**Comment by bentsherman** [comment]
I think he just means having the command-line functionality included in ACE gui. The console version can still be standalone.

But based on what you're saying I guess we would still want to have the GUI switch for KINC so that end users can either build KINC with a console-only interface or both console and GUI.

**Comment by spficklin** [comment]
Yep, Thanks @bentsherman, that's what I meant.  For folks who want the non-GUI version they can still build that.  But folks who have the GUI version should still be able to do command-line if they choose.

**Comment by 4ctrl-alt-del** [comment]
I will add command-line abilities to the GUI version so it can basically do everything(except maybe not MPI that would be strange) in the next release of ACE.

**Comment by spficklin** [comment]
I think MPI might be useful in both.  I can see the case where someone compiles KINC and wants one binary that can be used in a workflow on a cluster (using MPI) and then looking at result files with that same binary (with X11 forwarding or something).

**Comment by bentsherman** [comment]
Moving the highlights from this issue to ACE.
