### ISSUE TITLE
Clarification on missing values

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/KINC#140]
**This presents two connected issues.**

**First**, there is inconsistency in how the user inputs "NA" data:

For `import-emx` it is:
```
--nan <value>
Value Type: String
Default Value: NA
Expected token for expressions that have no value.
```
For `cond-test` it is:
```
--missing <value>
Value Type: String
Default Value: NA
The string that specifies the missing value in the annotation matrix (e.g. NA,
0, 0.0).
```

It is unclear on if this was intentional since these arguements are dealing with two seperate file types. This can be ignored if so.

**The second** related issue is that it is unclear in the documentation if the user should designate string missing values as:
```
--missing NA
```
OR
```
--missing "NA"
```

Online documentation appears to prefer quotes, while documentation shipped with kinc appears to prefer no quotes.

**Comment by spficklin** [comment]
This was unintentional.  I think we can make this fix for the 3.4.2 release to unify them.

**Comment by spficklin** [comment]
I think for backwards compatibility we should keep both but only document the `--nan` argument.

**Comment by spficklin** [comment]
Fixed with merged PR.
