### ISSUE TITLE
kinc-filter-rank.R `--top_n`

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/KINC#155]
The ` --top_n` option for `kinc-filter-rank.R` does not do what the documentation says. When I set it to `10000` it returned `16553789` edges. There are many edges which receive identical rankings, so while the file only goes up toi rank `10000` there can be many edges for a specific rank. If I select only the top 10,000 edges, I only will get to rank 192.

**Comment by spficklin** [comment]
@JohnHadish I think there might be confusion about what that option does.  It doesn't select _n_ edges, but the top _n_ ranked edges. Some edges can have the same rank.  Also, it will select each the top _n_ ranked edges per condition as well.

**Comment by spficklin** [comment]
I went ahead and fixed this issue so that it is no longer confusing.  PR #177 has been submitted.
