### ISSUE TITLE
Criterion option for GMM clustering, implement BIC and ICL

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#17]
Need to implement ICL criterion for GMM clustering, which requires entropy metric from the pair-wise GMM. Also need to provide a GUI / command line option to select criterion as a drop-down.

**Comment by 4ctrl-alt-del** [comment]
Drop down selection arguments are supported in ACE for analytics. They also work on the command line version.

**Comment by bentsherman** [comment]
GMM analytic now has a criterion option.and supports BIC and ICL.

**Comment by spficklin** [comment]
This is great!  Thanks Ben for implementing that.
