### ISSUE TITLE
Ask for visualization dependencies for KINC

### ISSUE THREAD

**Issue by Irisqing** [SystemsGenetics/KINC#176]
Hi, I was trying to run visualization part on nvidia system, but I'm not very familiar with docker system. I think you are trying to release kinc/3.4.2 which containing visualization dependencies. Could you tell me when you gonna release that? Or could you give me some suggestions about how to run kinc and python packages at the same time to make the visualization code run on docker system. 

Thanks!

**Comment by spficklin** [comment]
Hi @Irisqing I think we'll be able to make the release on Monday as well as the updated docker images.  I just had to do some last bit of testing on them and then have @bentsherman review it.

**Comment by Irisqing** [comment]
Hi Dr Ficklin,

Okay. That’s cool! Thanks for the update.

Best,
Iris

**Comment by spficklin** [comment]
@Irisqing the v3.4.2 release is now available.  The docker images have been built for this release and are currently uploading. They should be available in a few hours.

**Comment by spficklin** [comment]
Also, the online documentation has instructions for using the Docker images to run the visualizations:  https://kinc.readthedocs.io/en/latest/usage.html#using-the-3d-visualization-tool

**Comment by Irisqing** [comment]
Super!!!

Thanks,
Iris
