### ISSUE TITLE
Palmetto install broken

### ISSUE THREAD

**Issue by herber4** [SystemsGenetics/KINC#189]
**Broken install on palmetto**

./pbs-toolkit/modules/install-ace.sh v3.2.0
Lmod has detected the following error:  The following module(s) are
unknown: "openmpi/3.1.5-gcc/8.3.1-cuda11_0-ucx"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "openmpi/3.1.5-gcc/8.3.1-cuda11_0-ucx"

Also make sure that all modulefiles written in TCL start with the string
#%Module

Lmod has detected the following error:  The following module(s) are
unknown: "qt/5.14.2-gcc/8.3.1"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "qt/5.14.2-gcc/8.3.1"

Also make sure that all modulefiles written in TCL start with the string
#%Module

Info: creating stash file /home/herber4/ace/build/.qmake.stash
/software/spackages/linux-rocky8-x86_64/gcc-9.5.0/anaconda3-2022.05-zyrazrj6uvrtukupqzhaslr63w7hj6in/bin/mpic++: line 299: x86_64-conda_cos6-linux-gnu-c++: command not found
make[1]: *** [Makefile:5042: global.o] Error 127
make: *** [Makefile:49: sub-core-make_first] Error 2
/software/spackages/linux-rocky8-x86_64/gcc-9.5.0/anaconda3-2022.05-zyrazrj6uvrtukupqzhaslr63w7hj6in/bin/mpic++: line 299: x86_64-conda_cos6-linux-gnu-c++: command not found
make[1]: *** [Makefile:5042: global.o] Error 127
make: *** [Makefile:61: sub-core-install_subtargets] Error 2
(base) [herber4@node1155 bin]$ ./pbs-toolkit/modules/install-ace.sh v3.2.0 > pbs_output.txt
Lmod has detected the following error:  The following module(s) are
unknown: "openmpi/3.1.5-gcc/8.3.1-cuda11_0-ucx"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "openmpi/3.1.5-gcc/8.3.1-cuda11_0-ucx"

Also make sure that all modulefiles written in TCL start with the string
#%Module

Lmod has detected the following error:  The following module(s) are
unknown: "qt/5.14.2-gcc/8.3.1"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "qt/5.14.2-gcc/8.3.1"

Also make sure that all modulefiles written in TCL start with the string
#%Module

/software/spackages/linux-rocky8-x86_64/gcc-9.5.0/anaconda3-2022.05-zyrazrj6uvrtukupqzhaslr63w7hj6in/bin/mpic++: line 299: x86_64-conda_cos6-linux-gnu-c++: command not found
make[1]: *** [Makefile:5042: global.o] Error 127
make: *** [Makefile:49: sub-core-make_first] Error 2
/software/spackages/linux-rocky8-x86_64/gcc-9.5.0/anaconda3-2022.05-zyrazrj6uvrtukupqzhaslr63w7hj6in/bin/mpic++: line 299: x86_64-conda_cos6-linux-gnu-c++: command not found
make[1]: *** [Makefile:5042: global.o] Error 127
make: *** [Makefile:61: sub-core-install_subtargets] Error 2

**Comment by spficklin** [comment]
Hi @herber4 . Thanks for posting an issue.  

It seems to me as though the modules used by your script can't be found on Palmetto.  Perhaps the directory where the lmod modules are housed isn't in your path?

Otherwise, I don't have access to help debug issues on Palmetto. Perhaps @feltus can help or the Clemson Palmetto admins?

**Comment by spficklin** [comment]
Closed as per request from @feltus
