### ISSUE TITLE
Encoding of sample mask in cluster matrix

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#19]
Now that the clustering analytics are more or less complete, I wanted to figure out what all the different values for the sample mask are. Right now the analytics just write 1 or 0 to denote membership in a cluster, but I know that KINCv1 used a few additional values (looking at `PairWiseCluster.cpp`). Which ones do we still need?

Working list of values:
- 0: not in cluster
- 1: in cluster
- 6: not in cluster, removed by minimum threshold
- 7: not in cluster, removed by pre-clustering outliers
- 8: not in cluster, removed by post-clustering outliers
- 9: not in cluster, removed by nan-check

**Comment by 4ctrl-alt-del** [comment]
To make sure we did not run out of possible values each sample mask is a  single byte so it can hold values 0-255.

**Comment by bentsherman** [comment]
Did you and Stephen ever talk about using only 4 bits per sample? I think KINCv1 uses 6 or so different values...

@spficklin Can you comment on what other values are needed?

**Comment by 4ctrl-alt-del** [comment]
That's true we agreed on 4 bits so keep it to 0-15 sorry about that, mixed bits up in my head :)

**Comment by spficklin** [comment]
Here's the current meaning of the integer values in the sample string:
0: sample is not part of the cluster: both genes have valid expression data for the comparison
1: sample is part of the cluster.
6: sample is not part of the cluster:  one of the genes in the comparison had an expression value below a given threshold.
7:  sample is not part of the cluster:  the sample is an outlier prior to clustering
8: sample is not part of the cluster:  sample was first part of the cluster but was removed as an outlier of the cluster.
9: sample is not part of the cluster: one of the genes in the comparison has no/missing expression so the comparison can't be made

**Comment by bentsherman** [comment]
Okay, I can implement all of these values then. I remember seeing some of these things in KINCv1 so I will reference that code for default thresholds and computing outliers.

**Comment by bentsherman** [comment]
I added outlier removal today so we now have all of these cases covered. I also added check boxes for both pre- and post-outliers so that they can be enabled or disabled. In KINCv1 it looks like pre-outlier removal is commented out but post-outlier removal is not. @spficklin If you want, in the future I can enable these features by default but they probably need to be tested more.
