### ISSUE TITLE
Error messages more specific

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#2]
When loading an expression file if you don't provide the --nosample=NA then you get this error message if missing values are present:

KINC[GEM-log-no.emx]:>load GEM-log-no.txt 
Importing header information...
Importing gene samples[0%]...ACE Exception Caught!
What: EMatrix::InvalidFile
Location: void EMatrix::read_gene_expressions(std::ifstream&, AccelCompEng::Terminal&, const string&):428

Can you add a message to the Ace::assert function for a message that would help provide a bit more information about why the file is invalid. Otherwise the user doesn't really know why. Just that it's an invalid file.

**Comment by 4ctrl-alt-del** [comment]
I fixed this a while ago and forgot to update the issue, sorry! Resolved in commit 58d6bd4dde748e4f26ecd37495daedf645bba0ed back in January of this year.
