### ISSUE TITLE
Provide correlation analytics with optional cluster matrix input

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#20]
I'm pretty much done with the clustering analytics, we still need to test them thoroughly but they can run and they can output a cluster matrix. So it looks like the last piece needed to use GMMs in the KINC pipeline is to enable each correlation analytic to use a cluster matrix. I'm guessing this will be an optional argument so that the analytic would use it's current behavior if no cluster matrix is provided.

@4ctrl-alt-del were you already planning to do this? If so then it's ready for you, but I'm prepared to implement it myself if you're working on other things.

**Comment by 4ctrl-alt-del** [comment]
I was planning on doing this in the future. I am just starting to work on a minor version upgrade of ACE so it will not be months until I get started on it though. You are welcome to work on it in the meantime if you wish.

**Comment by bentsherman** [comment]
Okay, well if it's going to be that long for you then I will definitely take a crack at it.

**Comment by spficklin** [comment]
I'm a bit confused... what cluster matrix do you mean?

**Comment by bentsherman** [comment]
The CCM, the matrix that contains the number of clusters and the sample masks for each gene pair.

**Comment by bentsherman** [comment]
The Spearman and Pearson analytics both have a cluster matrix input now. For now they are required because I assume it will almost always be used, and otherwise it's easy to generate an empty cluster matrix with the GMM analytic.
