### ISSUE TITLE
SIngularity image for version1

### ISSUE THREAD

**Issue by wpoehlm** [SystemsGenetics/KINC#25]
It is difficult to compile KINC 1.0 in new environments, with it often being necessary for the user to modify the makefile significantly.  Mixmodlib is not typically installed as software modules on HPC clusters (ie palmetto or comet), and we've had issues with memory leaks in the past.  I think that having a singularity image for a stable kinc build would be helpful.  It will be a large image, but would save users a lot of headache when trying to compile kinc 1.0.

**Comment by bentsherman** [comment]
Regarding this issue and your other issue on documentation, I can revamp the README to include installation and usage instructions. Between that and a little work on the Makefile I think I can make KINC a little more straightforward to build so that a Singularity image isn't necessary.

**Comment by feltus** [comment]
Thanks Ben. Let's make sure that the right  mixmod library is correctly pointed to as a dependency. I think KINC might be pointing to a known memory leak mixmod build  in the  old version. I might be wrong.  Very possible.  Possibly likely :).


Sent from my Verizon, Samsung Galaxy smartphone

**Comment by bentsherman** [comment]
Alright, I've added instructions for installing mixmod. You shouldn't have to edit the Makefile at all with this setup; if you look at the environment variables I use with `$INSTALL_PREFIX`, you can actually use this setup to install any software to `$HOME/software`, and use it just like if it were installed globally. So that should make building and using KINC much smoother.

I also added an example usage with the Yeast dataset based on the scripts that I have, let me know if you guys would like to add or change anything.

**Comment by wpoehlm** [comment]
Thanks Ben, that helps a lot!  I still think that an image would be helpful.  For example, I'm trying to compile  mixmodlib on Comet and the g++ version is causing issues:
```
Scanning dependencies of target mixmod_newmat
[  1%] Building CXX object SRC/CMakeFiles/mixmod_newmat.dir/NEWMAT/bandmat.cpp.o
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [SRC/CMakeFiles/mixmod_newmat.dir/NEWMAT/bandmat.cpp.o] Error 1
make[1]: *** [SRC/CMakeFiles/mixmod_newmat.dir/all] Error 2
make: *** [all] Error 2
[  1%] Building CXX object SRC/CMakeFiles/mixmod_newmat.dir/NEWMAT/bandmat.cpp.o
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [SRC/CMakeFiles/mixmod_newmat.dir/NEWMAT/bandmat.cpp.o] Error 1
make[1]: *** [SRC/CMakeFiles/mixmod_newmat.dir/all] Error 2
make: *** [all] Error 2
```

I also have to install other dependencies without having root access.  Definitely something I can work through but having the image would help especially since we want to run this in multiple resources(bridges, comet, osg, palmetto, cloud, etc...).  I'll try to build the image and let you know if I get stuck

**Comment by bentsherman** [comment]
If this is something urgent then I'm willing to go ahead and make one, but I'd like to explore some of these issues you're having to see if they can't be solved by simpler means. In the grand scheme of things, KINC's build process is pretty simple and the dependency chain is pretty simple too.

This might be easier to do in person, but I'd actually like to learn about some of the details for these systems, especially bridges and comet, like what software they provide. For example, that `cc1plus` compiler may have a completely different interface from `g++`, so it may just be incompatible with our Makefile.

**Comment by wpoehlm** [comment]
The image isn't urgent but I'd like to get KINC running on our xsede allocation soon.  Would you have time tomorrow or Friday to meet about this?

**Comment by bentsherman** [comment]
We can go over it during the Friday meeting.

**Comment by bentsherman** [comment]
@wpoehlm If you're done working on that Singularity recipe could you push it to the `version1` branch so that I can close this issue?

**Comment by wpoehlm** [comment]
@bentsherman Done, thanks!
