### ISSUE TITLE
Optimize MPI / OpenCL parameters in analytics

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#28]
Since we can query OpenCL device information, I'm wondering if there is an optimal way to choose the block size and kernel size based on the capacity of the OpenCL device. For example, set the block size to the number of compute units and the kernel size to the maximum workgroup size. If I understand everything correctly, that would keep the device fully utilized.

However, I wonder about the trade-off of having fewer blocks with proportionately more kernels. For example, for a device with 10 compute units and max workgroup size of 1024 (like my GPU), you could have 10 blocks with 1024 kernels, or 5 blocks with 2048 kernels, or 1 block with 10240 kernels... I think each case would keep the device fully utilized but perhaps with different ramifications for the I/O between host and device. Perhaps if we could automate that trade-off, then we would be set. This would all be very useful once we start using MPI on a cluster of nodes that may not have uniform capabilities.

**Comment by 4ctrl-alt-del** [comment]
That sounds like a good idea for the future. I will keep that in mind.

**Comment by bentsherman** [comment]
While playing with CUDA support last night, one solution that I thought of for this trade-off is to simply let the user choose the block size and then set the kernel size automatically based on the device resources. That is, given the block size, we can distribute the total number of `COMPUTE_UNITS * MAX_WORKGROUP_SIZE` kernels (or `SM_SIZE * MAX_BLOCK_SIZE` in CUDA) across each block.

After all, blocks are a feature of ACE, but kernels are a feature of OpenCL/CUDA, so it makes sense to allow the user to tune the ACE-level feature, but then optimize device usage regardless of the choice of block size. Keeping in mind that it would probably be advantageous to use a block size that divides evenly into the total device resources

I still need to collect some performance data to see how these arguments affect run-time, just to see if this idea is valid.

**Comment by feltus** [comment]
Keep those performance numbers.  It might make a good figure in a paper ;).

**Comment by bentsherman** [comment]
After a few small tests, here are some observations that I made:

- Increasing the kernel size definitely improves performance, even above the device's compute capacity to some extent
- Increasing the block size didn't seem to affect performance. I know that in CUDA you have to explicitly use separate streams in order to overlap kernel calls with memory transfers, maybe the OpenCL blocks are still sharing the same command queue?
- Running MPI with 1 master / 1 GPU worker is much slower than just the GPU without MPI, as I suspected. Since the worker has to process one block at a time, it is difficult to keep the GPU busy between blocks. Increasing the MPI block size increases performance, since it decreases the amount of time waiting for blocks.

So at this point we really have three parameters that we need to optimize for performance (and it is the same setup for both MPI+OpenCL and MPI+CUDA):
- Block size: probably should be at least 2-4 so that kernel execution / memory transfer can be overlapped like Josh said, allow the user to set
- Kernel size: should be maximized to match or slightly exceed GPU capacity, probably can be automated
- MPI block size: this one's slightly trickier; increasing it improves GPU bandwidth, but decreasing it may improve load balancing. I think for larger GEMs we can just make it as large as possible because there will be so much work anyway that the master will still be able to load balance.
- Initial MPI blocks: number of work blocks to send to each worker at initialization; needs to be high enough to keep workers busy assuming that a new block is sent for each completed block

For the purposes of the ACE paper, the current defaults should be fine mostly; you may want to adjust the kernel size to match GPU capacity, and I'll probably increase the MPI block size as much as I can before final testing.

**Comment by feltus** [comment]
We could ask an MPI expert if you think it is worth the time.  Walt Ligon and.a guy at LSU I know would give some thought.

**Comment by bentsherman** [comment]
I just ran a quick experiment where I varied the MPI block size from 1K to 256K (in powers of 2) and timed GMM on Yeast-500 (Yeast with just the first 500 genes). Using default block size of 4 and kernel size of 4096. As a baseline, using just one process with GPU it took 80-90 s. Then for the MPI tests I had two processes, a master and a worker, so the master and worker just send MPI blocks back and forth. Essentially identical to the baseline setup but with MPI overhead, so that I can measure it.

As expected, at lower MPI block sizes it takes 2-3x longer, and as the MPI block size increases, runtime decreases and actually approaches the baseline runtime. At some point around 32K, the runtime begins to flatten and at larger values like 256K it evens increases slightly. So it seems like as long as the MPI block size is large enough to keep the GPU busy, we really don't see much MPI overhead at all. I think the communication might be offset by the benefit of having a master node dedicated to all of the output file I/O.

So I guess that setting the MPI block size to a constant 32K turned out to be a lucky guess! I think our default values for all of these parameters are good for now.

**Comment by bentsherman** [comment]
Updating with the current state of these parameters:

- Work-block size: determined indirectly by analytic, which must compute the total number of work blocks as `total steps / block size`. Should be at least as large as kernel size.
- Kernel size: determined by user as analytic argument. Should be at least as large as max workgroup size (which is typically 1024).
- OpenCL thread size: formerly "block size", determined by ACE settings. Should be at least 2 to fully utilize GPU hardware.
- MPI buffer size: determined by ACE settings, should be large enough to keep workers busy during the time between sending result blocks and receiving new work blocks.

**Comment by spficklin** [comment]
Do we need to re-evaluate these with all of the new changes to ACE?  Also, should we provide the ability for end-users to tweak these settings via the command-line?

**Comment by bentsherman** [comment]
My comment on May 30 should be up to date with ACE. Based on what I said then, the kernel size, thread size, and MPI buffer size are all configurable through the command line or GUI. For now they are set to reasonable defaults and the user can change them if needed, and I think that's the best approach for now.

**Comment by bentsherman** [comment]
There's another performance parameter which we haven't considered up to this point: the local work size (or block size in CUDA). I recently renamed kernel size to global work size and added a parameter for the local work size. Normally, we compute the local work size as the maximum size allowed by the kernel, which is determined primarily by the number of local variables used by the kernel. I assumed that this way we would maximize GPU utilization.

But in an interesting turn of events, that is not the case at all. I just ran some tests where I varied the local work size from 16 to 1024 in powers of two, and these are the optimal values I got:

Pearson: 128
Spearman: 32
GMM/Pearson: 16
GMM/Spearman: 16

These numbers actually make sense to me now after doing some reading on GPU optimization. Pearson has a larger optimal size because it's kernel is relatively simple, Spearman is a bit more complex, and GMM is just off the charts. The GMM kernel has way more local variables and branching (if statements and loops), and it uses a lot of global memory. My hypothesis is that running fewer threads actually decreases global memory contention so much that it increases performance. I'll have to investigate these things myself later on.

Anyway, the main point for you @spficklin and @4ctrl-alt-del is that you should try using a lower `--lsize` value like 16 or 32 when you run KINC. There's little performance difference between those values but I saw a sharp performance drop at 512 which is representative of the default behavior so you might really benefit from this setting.

**Comment by spficklin** [comment]
Hi @bentsherman .   So, to clarify, here's what I used when I ran KINC with 33K x 144 GEM matrix using GMM and Spearman (17 hours).

```
    --bsize 32768 \
    --gsize 4096 \
    --lsize 0
```
I copied those values from what qkinc when I tried a test run, then used them for the command-line run. 
 I'm not sure why lsize is 0.  I'm guessing a value of 0 might be interpreted as not set and the default would be used?   I'll restart it with --lsize set at 32 and see what happens.

**Comment by bentsherman** [comment]
That's correct, `--lsize` is 0 by default which invokes the maximum-size method. I'm curious to see how much speedup you get on a large run like what you've been doing.

**Comment by spficklin** [comment]
Adding back on the release blocker so that we remember to document this for users.

**Comment by bentsherman** [comment]
Added to documentation.
