### ISSUE TITLE
Import/export cluster matrix analytics

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#29]
I think it would be helpful to be able to import output data from KINCv1 into the new format so that we can compare them easily with the new version. The import analytic would take a directory of cluster data produced by similarity and produce both a cluster matrix and a correlation matrix, and vise versa for the export analytic. It also might give us another window into the CCM issues we've been having.

I think I will start working on this when I have time.

**Comment by bentsherman** [comment]
I was able to write up these analytics pretty quickly, right now they only work on a single file rather than a directory tree. You can combine the directory tree into one file like this:
```
cat clusters-sc/**/*.txt > net.txt
```

You can also just provide one of the cluster files in the tree. I haven't gotten it to work with a concatenated file, I think because `GenePair::Base` assumes that you're saving gene pairs in order? @4ctrl-alt-del is this true?

Also, I'm encountering the same problem from before in that I can't open either the CCM or the CMX because they seem to be corrupted. I'm going to go ahead and push my changes so that we can try out these analytics on different systems...

**Comment by 4ctrl-alt-del** [comment]
Yes for any sparse matrix that uses GenePair::Base you MUST input the data in order. Order is determined by gene x, gene y, and cluster with most significant to least significant in that order.

**Comment by 4ctrl-alt-del** [comment]
Also gene y must be less than gene x.

**Comment by bentsherman** [comment]
Okay, I found a way to sort the data in the cluster files with version sort. So the proper method:
```
sort -V clusters-sc/**/*.txt > net.txt
```

I will also update the import/export analytics to operate with this assumption that the clusters are sorted.

**Comment by bentsherman** [comment]
Barring the CCM bug, these analytics seem to work fine, closing this issue.

**Comment by spficklin** [comment]
Awesome!
