### ISSUE TITLE
open -> select -> load shortcut

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#3]
To keep from needing to execute open, select and load commands I think we need  a shortcut command that can do all three at once.  Especially if loading fails then you have to do all three again....

**Comment by 4ctrl-alt-del** [comment]
Sure, that requires a change to ACE however not KINC.

**Comment by 4ctrl-alt-del** [comment]
Moved to ACE issue at https://github.com/SystemsGenetics/ACE/issues/19
