### ISSUE TITLE
GraphML output

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#30]
KINC should output a GraphML version of a network that has all of the usual KINCv1 output attributes on the edges.

**Comment by bentsherman** [comment]
Added the initial Extract analytic today, I will add GraphML output next. Also need to provide EMX to Extract analytic so that it can write sample masks for gene pairs with only one cluster.

**Comment by bentsherman** [comment]
@spficklin Could you provide an example GraphML file for a small network or subset? Or a more detailed description of the edge attributes and their names?

**Comment by spficklin** [comment]
@bentshermahan sorry I haven't got to this yet. It's not urgent, but it will really be helpful to have this when we start loading networks into GeneNetEngine.   I'll provide an example file soon.  We need to figure out what all the edge attributes need to be.  I'm marking this with the label 'waiting for input' so I remember to send you something.

**Comment by spficklin** [comment]
Ben I see you've done this already! This is great.  Until we start loading networks into GeneNetEngine I probably won't have any input for you.  So, I'm going to close this out and when the time comes I'll post a new issue with the request.

Thanks!
