### ISSUE TITLE
RMT considerations

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#31]
The RMT analytic still assumes that input correlation matrix only has one cluster per gene pair, need to refactor it so that it reads all clusters.

Also it might be good to have RMT just write the recommended threshold to the output log instead of generating a new correlation matrix, since we're going to make another analytic for extracting the net list anyway.

**Comment by bentsherman** [comment]
@spficklin I know we've talked about this before, but a second coat of paint wouldn't hurt -- how do you structure the prune matrix (or "cut matrix" in KINCv1) in order to account for multiple clusters?

**Comment by spficklin** [comment]
Hey @bentsherman.   In KINC v1 the matrix created for thresholding is a pairwise "cluster" matrix as opposed to a pairwise "gene" matrix.   So each cluster gets it's own row/column in the matrix.   After RMT is done then those clusters that are above the threshold become unique edges in the output network.   

RMT really only cares if the matrix looks random or not, so it doesn't matter what you put into (e.g. correlations from paired genes or correlations from clusters from paired genes).

**Comment by bentsherman** [comment]
So I've devoted a little bit of time over the past few days working on this, and I ran into some questions that arise when considering a "cluster" matrix as you said. If there is a row/column for every cluster rather than every gene, you introduce elements which represent correlations between clusters. For example, assuming max clusters of 5, each element in the gene matrix essentially is replaced by a 5x5 sub-matrix, where the diagonals represent the actual correlations and the other spots represent... what does it represent? It doesn't really make sense to talk about something like "the correlation between cluster 1 of gene X and cluster 2 of geneY"

So at this point I can fill the diagonal.. but what do I do for all of the other "inter-cluster" elements introduced by replacing the gene matrix with a cluster matrix?

**Comment by feltus** [comment]
An edge, 2 edges, or more edges at different gene expression intensities in different sample contexts is very meaningful.  A lack of an edge in a mode is meaningful.  Remember there are thousands of "conditions"  so ideally we would like to see if there are thousands of modes w/wo correlation in an organism's "expression space".  Lets discuss in person :).

**Comment by spficklin** [comment]
Good question @bentsherman.  I'm glad you stopped to think on that.  I think you're right we've got an issue.   I was correct in what I told you that KINC v1.0 is doing... but your questions made me go back and look at the code.  There are two problems with this current approach.  1) We are padding the matrix with rows/cols of zeros (indicating no correlation) when a comparison doesn't have the max number of clusters; 2) and we are potentially lining up clusters in one gene comparisons (e.g. gene X vs gene Y) with clusters in other gene comparisons (e.g. gene X vs gene Z) that may not have the same samples in the clusters with the same number (we are using cluster indexes to order the rows/cols).  I honestly am not sure of the effect that the first issue creates, but the second seems like it would introduce some level of noise.

I have a suggestion for what we might be able to do. I'll bring it up in our next meeting.

**Comment by bentsherman** [comment]
The RMT analytic is now cluster-aware. I'll leave this thread open for discussing the algorithmic considerations of RMT.

Transitioning from a "gene pair" correlation matrix to a "cluster pair" correlation matrix essentially replaces each correlation element with a diagonal matrix of cluster correlations; the overall prune matrix is actually quite sparse. I'm not sure how that affects the eigenvalues or the thresholding, but it's what KINCv1 did and it seems to have worked for you guys so far.

**Comment by spficklin** [comment]
Thanks @bentsherman for fixing this, at least to match the KINC v1 behavior.  We still have a problem with RMT in general because of the cluster (as I described above) so we need to adjust our approach.  I'm marking this with the label "needs_fixing" so we remember to do that.

**Comment by bentsherman** [comment]
I had an idea for dealing with this cluster issue. What if instead of doing a "cluster-pair" correlation matrix we do the original gene-pair correlation matrix, but when applying a threshold, we keep an edge if any of the modes of the gene pair have a sufficiently high correlation. The idea is that since modes represent conditions, a KINC network can be understood as a union of several condition-specific networks, so maybe we only need to consider the mode with maximum correlation when doing a threshold test like RMT or power-law.

**Comment by spficklin** [comment]
Yes, I think this sounds like a reasonable approach.   

Although we have a problem with RMT thresholding for condition-specific networks.  Right now we are bypassing the KINC threshold step and using KINC.R for network creation after KINC similarity is run. For example, we export a network at some arbitrarily low threshold (e.g. 0.70).  Then we import that network into KINC.R along with an annotation matrix file that maps experimental conditions to each sample.   KINC.R assign a p-value to each edge (i.e. GMM cluster) for a given experimental condition (e.g. heat exposure, control, inoculated, etc.).  The user can then specify a set of p-value filters to get a list of edges that are condition-specific.

However, this approach is clunky to do and it requires the user to leave KINC to work with KINC.R.  If we could do this filtering with KINC it would save a lot of time and we could go back to using RMT thresholding too. To make this happen with KINC, we would need to make a new data class for storing p-values for conditions and a new analytic for calculating those p-values. Then we would need to adjust the RMT analytic to use the new p-values data file for thresholding. User's wouldn't need KINC.R to do the conditional thresholding, which I think makes KINC even more powerful as as stand-alone tool.

**Comment by bentsherman** [comment]
You're talking about the Fisher test? I've been interested in trying that method for a while now, I think it would be a great feature to have in KINC. If you could send me an example annotation file (either for Yeast or another GEM with the GEM file as well), I can start looking into it.

**Comment by spficklin** [comment]
Hi @bentsherman I think it might be easier to chat on it.  Let's try to schedule a time to meet.

**Comment by bentsherman** [comment]
@spficklin Would love to discuss this at our next co-lab meeting.

In other news, we are going forward with the approach of selecting one cluster per gene pair in order to eliminate the issues stemming from the cluster-cluster matrix. RMT now provides three options for "pairwise reduction": you can select the first cluster, the cluster with the highest correlation, or a random cluster. For now we are trying the first option.

@spficklin @4ctrl-alt-del I also changed the eigenvalue code to use LAPACKE instead of GSL because it's way faster for what we need. Like an order of magnitude faster. Unfortunately it requires another dependency... any LAPACKE implementation will do, the install docs specify openblas because it's easy to install. We already have openblas on the Palmetto cluster, but you guys may have a different LAPACKE implementation on Kamiak. Let me know if you need any help setting up that dependency. Sorry again for the added inconvenience but I think the speedup it gives us is quite worth it.

**Comment by 4ctrl-alt-del** [comment]
@bentsherman please look at the urgent issue I made I've been trying to get lapacke working for two days now unsuccessfully on kamiak... they have openblas modules but none of them work.

**Comment by bentsherman** [comment]
At this point I think it's safe to say that we've dealt with the issues described in this thread. I'm going to close this thread and start a new one for the discussion on integrating features from KINC.R.
