### ISSUE TITLE
CL_OUT_OF_RESOURCES with GMM OpenCL

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#32]
I've had a few cases now on Palmetto where when I try to run GMM OpenCL I get this OpenCL error. It has occurred as early as 0% and as late as ~50%, and it has occurred for both single-GPU and multi-GPU. However, it doesn't always happen. I've been able to produce a Yeast CCM multiple times on Palmetto, although I think it was on an interactive node.

Unfortunately this OpenCL error is broadly defined, so there are a few possibilities that I'm aware of:
- the device ran out of kernel / memory resources
- a segfault occurred in a kernel (such as invalid memory access)
- a kernel took too long to execute

I'm interested to see if this problem occurs on Kamiak, but either way I'll be investigating these possibilities today. I've only ever seen this problem on Palmetto, never on my laptop, so there could be some clashing caused by sharing resources with other users. As we've said before, PBS doesn't always hide GPU resources perfectly from users who didn't request them.

**Comment by spficklin** [comment]
Could it be the case where someone is already using it?

**Comment by bentsherman** [comment]
Yeah so there was one time where I checked each node and on one of the nodes there was some VM process running on the GPUs. I don't know how much it was consuming but I think that node got this error. Our access to GPUs has improved recently but the GPU nodes are still heavily used for their newer hardware and interconnect, so it's hard to get a node where no one else is on the other CPU cores, much less 10 nodes. That's why I'd like to see what happens on Kamiak.

**Comment by bentsherman** [comment]
I haven't run into this problem during the last few days... I know that any of the GPUs older than the K20s on Palmetto immediately give this error, so I've just been requesting K20 nodes. If I go for a while without this issue then I'll close it.

**Comment by bentsherman** [comment]
Closing this issue since it hasn't occurred in a while. K20 GPUs and newer seem to work fine with OpenCL.
