### ISSUE TITLE
No Qt support on Kamiak

### ISSUE THREAD

**Issue by 4ctrl-alt-del** [SystemsGenetics/KINC#33]
Hey @bentsherman so I have ran into a wall trying to run the new KINC on kamiak. It has no Qt support. I tried to install it manually but qt only offers GUI only installers now to install qt apparently. I am at a bit of a loss what to do. All I need it qtcore but I can't found its source did you run into this?

**Comment by bentsherman** [comment]
Yeah we also had to build Qt from source on Palmetto but I just used the full 5.9.2 source a while back. I can send you a script I wrote to do the whole thing from download to install.

**Comment by 4ctrl-alt-del** [comment]
Sending that script would be fantastic thank you!

**Comment by bentsherman** [comment]
Actually, my script doesn't do _everything_... it doesn't download the archive for you because it's huge. Here's the script:
```
VERSION=5.9.2
JOBS=16

# extract archive
tar -xvf qt-everywhere-opensource-src-$VERSION.tar.gz

# create build directory
rm -rf qt-$VERSION
mkdir qt-$VERSION

# build and install Qt
cd qt-$VERSION
echo -e 'o\ny\n\n' | ../qt-everywhere-opensource-src-$VERSION/configure -prefix .
gmake -j $JOBS
gmake install -j $JOBS
```

I see what you're saying now, the Qt website is very different, but I'll try to point you in the right direction: [this page](https://doc.qt.io/qt-5/linux-building.html) has more instructions for building from source and [this page](https://www1.qt.io/offline-installers/) looks like it has links to source packages. You may want to go through the instructions step by step rather than just running my script... you'll probably have to adapt it to work with your environment.

EDIT: [Qt 5.10 source tarball](http://download.qt.io/official_releases/qt/5.10/5.10.1/single/qt-everywhere-src-5.10.1.tar.xz)

**Comment by spficklin** [comment]
Hi @4ctrl-alt-del I'll get it installed for you.

**Comment by spficklin** [comment]
So I've got QT 5.10.1 installed on Kamiak.  ACE is not building though... I'm getting this error:

> mpic++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I../../src/core -I. -I../../../../qt-5.10.1/5.10.1/gcc_64/include -I../../../../qt-5.10.1/5.10.1/gcc_64/include/QtGui -I../../../../qt-5.10.1/5.10.1/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I../../../../qt-5.10.1/5.10.1/gcc_64/mkspecs/linux-g++ -o metadatamodel.o ../../src/core/metadatamodel.cpp
> ../../src/core/metadatamodel.cpp(402): error: class "std::initializer_list<QList<QString>>" has no member "at"
>            map->remove(keys.at(row+i));

That's message seems wrong to me because according to the online docs QList does have a method named "at".  http://doc.qt.io/qt-5/qlist.html#at

**Comment by bentsherman** [comment]
@spficklin Did you use the `mpi-hacks` branch? The `develop` branch may be broken right now since Josh is still working on the metadata system.
```
git checkout mpi-hacks
```

**Comment by 4ctrl-alt-del** [comment]
metadatamodel.cpp doesn't exist anymore in the develop branch so it isn't that. I just tried running qmake on kamiak and it says command not found so wherever you installed qt stephen I can't see it.

**Comment by bentsherman** [comment]
You may have to update some environment variables to use your Qt build, I'm not sure what the installer does for you in that regard. Something like this:
```
export QTDIR="$HOME/qt-5.10.1/5.10.1/gcc_64"
export PATH="$QTDIR/bin:$PATH"
```

Regarding the compiler error, if it is in fact on the `mpi-hacks` branch then maybe it has to do with your C++ compiler. What version of `g++` / `mpic++` are you using? I have 5.4.0 which works for me.

**Comment by spficklin** [comment]
You can load QT with 'module load qt' and it should add everything you need to your environment.

**Comment by spficklin** [comment]
I can compile both ACE & KINC on Kamiak... marking resolved,
