### ISSUE TITLE
Request for Kendall Tau Correlation Analytic

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/KINC#38]
Kendall Tau is similar to Speamans, but is more robust for smaller sample sizes. This may make for a nice addition.

**Comment by bentsherman** [comment]
Looks pretty similar to Spearman like you said, I should be able to add this pretty quickly after some other issues have been taken care of.

**Comment by JohnHadish** [comment]
Awesome, thank you.
Just for fun, I went to the literature to back up what I had been reading on blogs, and I found these two nice articles that I thought I might share:

The first is a 1997 paper that briefly argues why Tau is better than Pearson's (robust to outliers, non-parametric, capable of accepting a much wider class of bivariate distributions) and then goes on to test it with an artificially created data set. 
https://onlinelibrary.wiley.com/doi/epdf/10.1111/j.2044-8317.1997.tb01100.x

The second is a 2000 paper that compares Speaman's, Pearson's and Kendall's in a similar fashion to the first. I am not going to pretend like I understand every calculation they did, but the table on page 26 is a really nice summary of how these different tests preform.
https://link.springer.com/content/pdf/10.1007/BF02294183.pdf

I also really like that Kendall Tau actually makes intuitive sense when you go through the calculations, unlike Spearmans. I know that this doesn't matter in the grand scheme of things since it only matters how well they preform, but it is kind of comforting to me when I can figure out the mechanism without having to hunt down a mathematician. 

Thank you again.

**Comment by JohnHadish** [comment]
Bump

**Comment by bentsherman** [comment]
@JohnHadish wanted to let you know that Kendall Tau is supported in the Python script `similarity.py`, in the `develop` branch. So you can play with it on small datasets now, and later on I will add it to KINC so that you can use it at scale.

**Comment by spficklin** [comment]
I think we're agreed this is a good analytic to add.  However, let's close out issues that are getting old with no progress.  I've added the tag 'For the Future' so we can search for these that we know we want to add later but don't have time now.  Please reopen if anyone feels different.
