### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#39]
Need to develop a suite of unit tests as our code begins to solidify. Going to try to document some tests here so that I remember to develop them later:

Data types: test writing to file / reading from file
- `CCMatrix`
- `CorrelationMatrix`
- `ExpressionMatrix`

Algorithms: test with small data (Iris / Yeast), verify results against other libraries (gsl, sklearn)
- `GMM`
- `KMeans`
- `Pearson`
- `Spearman`

Analytics: test all applicable capabilities with small data, verify results across capabilities
- import/export
- similarity
- RMT
- extract

**Comment by bentsherman** [comment]
All data and analytic objects (except for extract) have basic unit tests. Things that remain:
- test clustering, correlation algorithms, outlier removal
- verify output data for all analytic tests
- test all capabilities (similarity)
- replace random data with Yeast data where applicable?

**Comment by bentsherman** [comment]
I was almost able to upgrade one of my analytic unit tests (ImportExpressionMatrix) to ACE v3, but I can't find a way to run analytics synchronously because `QTimer` calls don't work in the unit tests.

From some further research, I think the best course will be to follow Qt's suggested paradigm and split each test class into a separate executable and use `QTEST_MAIN` so that QTimer calls work. The alternative is to manually create a QApplication or QEventLoop but that route isn't immediately obvious to me.

**Comment by bentsherman** [comment]
Best practices for Qt unit testing: https://wiki.qt.io/Writing_Unit_Tests

**Comment by spficklin** [comment]
@bentsherman is this something being actively worked on or should we close it out to keep issues we don't have time for and want to deal with later out of the queue.

**Comment by bentsherman** [comment]
This issue is complementary to #96. At some point it would be nice if someone could address the issues I've raised here about the Qt unit tests. But honestly doing #96 would be more useful. So I will follow suit with @spficklin and label this as something for the future.
