### ISSUE TITLE
--nosample on EMatrix data object

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#4]
The --nosample argument should be renamed to --missing as the word 'sample' can be confusing.

**Comment by spficklin** [comment]
Also... let's change the text "Old file xxxxxx opened." to "Existing file xxxxxx opened" when opening an existing file..  I know... nit picky stuff...

**Comment by 4ctrl-alt-del** [comment]
Changed --nosample to --missing with commit ecafe2143cc32df1319854af2e06109568b2e882. I cannot change the "old file xxx opened" because that is part of ACE not KINC.

**Comment by 4ctrl-alt-del** [comment]
Moved part of issue that is ACE to new ACE issue at https://github.com/SystemsGenetics/ACE/issues/18
