### ISSUE TITLE
KINC not using all GPUs?

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#43]
I'm running KINC on the yeast data on Kamiak and I'm wondering if it's using all GPUs.  When I run KINC stand-alone it sees 4 GPUs.  There are 2 K80s.  If I run KINC with 2 tasks per node then GPU with index 0 shows about 50% busy (my observation).  If I run KINC with 4 tasks per node then the GPU with index 0 is 100% busy. However,  GPUs 1,2 and 3 show 0% utilization. 

I'm using this command to check on utilization:

> nvidia-smi -q -g 0 -d UTILIZATION -l 1

Thoughts?

**Comment by spficklin** [comment]
Oh, I just found a way to see what process are running on the GPUs.  In fact all 4 are running on the first GPU with none running on the others 3: 

 ```
   [Processes
        Process ID                  : 80379
            Type                    : C
            Name                    : /data/ficklin/software/KINC-3.1.1/kinc-cli
            Used GPU Memory         : 210 MiB
        Process ID                  : 80380
            Type                    : C
            Name                    : /data/ficklin/software/KINC-3.1.1/kinc-cli
            Used GPU Memory         : 210 MiB
        Process ID                  : 80381
            Type                    : C
            Name                    : /data/ficklin/software/KINC-3.1.1/kinc-cli
            Used GPU Memory         : 210 MiB
        Process ID                  : 80382
            Type                    : C
            Name                    : /data/ficklin/software/KINC-3.1.1/kinc-cli
            Used GPU Memory         : 210 MiB](url)
```

**Comment by spficklin** [comment]
@bentsherman explained by email that current ACE/KINC defaults to always using the first GPU.   And future version of ACE/KINC will balance out the load among the visible GPUs.  So that makes sense now.  

But, it seems SLURM will give me the GPU assigned to my job with the SLURM_JOB_GPUS environment 
variable.  KINC apparently sees all of the GPUs regardless how many I told it I wanted to use.   So, I think even though future ACE/KINC will better divide up the workers by the visible GPUs, I will still need to provide the indexes to the GPUs that SLURM tells me I am allowed to run on.

Unfortunately, the format of the SLURM_JOB_GPUS is not defined in any documentation that I've looked at, so I'm not sure if it's list separated by commas or what...

**Comment by bentsherman** [comment]
I think you can also use the `CUDA_VISIBLE_DEVICES` environment variable to control which GPUs can be seen by a node. More information here:

https://devblogs.nvidia.com/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/
