### ISSUE TITLE
Use all GPUs?

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#44]
According to @4ctrl-alt-del the ability to use all GPUs on a node will be available in the next update to ACE and then KINC has to be adjusted to use the newer version of ACE.    I have access to 20 GPUs, 4 each on 5 nodes.  But, I'm only currently able to use 1 at a time on each node. I've found that on Kamiak that 4 processes will keep 1 GPU fully busy.  If I could launch a KINC job that can run 60 MPI processes that would be awesome.  I was able to process 30% of the yeast data in 2 hours using 10 MPI processes.  So, would it be possible to tweak ACE/KINC such that I can use all the GPUs available to me before the next version comes out?  This way we can start cranking on networks.

**Comment by bentsherman** [comment]
It looks like you can use the `CUDA_VISIBLE_DEVICES` environment variable to control OpenCL devices as well. So for example:
```
CUDA_VISIBLE_DEVICES=2

# KINC will only see the third GPU (device 2)
./kinc-cli run ...
```

If you can figure out how to set that environment variable to the local rank on each node before running KINC, that should do the trick.

**Comment by spficklin** [comment]
Awesome. Thanks. I can get the device ID from SLURM and this means I can now run multiple KINC jobs at once that won't clobber each other.  But I'm not sure how to set that variable for MPI jobs so I can run one KINC job that can use all GPUs at once.  Is there a way to set environemnt variables separately for each MPI job?

**Comment by bentsherman** [comment]
I don't know. I would check the srun command to see if you can pass environment variables as arguments. I think you can do that with mpirun, and OpenMPI provides environment variables for things like size and rank.

**Comment by bentsherman** [comment]
Closing since Stephen figured out how to do this on Kamiak.
