### ISSUE TITLE
Save sample string with 4-bit elements in CCM

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#45]
I know we've said that we're saving sample strings with 4-bit elements instead of 8-bit in the CCM format, but as far as I can tell, the CCM code is still saving 8-bit values. @4ctrl-alt-del can you confirm or deny? We should make sure this is implemented at some point.

**Comment by 4ctrl-alt-del** [comment]
Yes I can confirm it uses one byte. Code would need to be added to compress and expand two values from one byte.

**Comment by bentsherman** [comment]
Something about the way you just described the solution made it totally clear to me how to implement it, I can probably add this pretty quickly.

**Comment by bentsherman** [comment]
CCMatrix now uses 4-bit values, and CCM files just got halved in size.
