### ISSUE TITLE
Compile issues

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#46]
When trying to compile KINC v3.2.0 on kamiak I get the following errors:
```
/usr/bin/ld: cannot find -lmpi_cxx
/usr/bin/ld: cannot find -lkinccore
```
I had to edit the makefile to remove the -lmpi_cxx and I had to alter the path of the build directory where libkinccore from this:
```
-L/data/ficklin/software/src/KINC/src/../../build/libs
```
to this:
```
-L/data/ficklin/software/src/KINC/src/../build/libs
```

**Comment by spficklin** [comment]
Also, it would be nice to have a 'make install' similar to ACE

**Comment by 4ctrl-alt-del** [comment]
Fixed compile bug and released in version 3.2.1 right away since that caused building the software to fail. Also KINC 3.2.0 and up does have a make install and it works just like ACE.

**Comment by spficklin** [comment]
Thanks for the quick fix.   Can you give an example for how to compile and install?  I did try to use the PREFIX and I ran a make install but it didn't work.

**Comment by 4ctrl-alt-del** [comment]
qmake ../src/KINC.pro PREFIX=$HOME/software MPICXX=no
make qmake_all
make
make qmake_all (install will NOT work unless you run this again after compiling)
make install
