### ISSUE TITLE
Unknown error with RMT.

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#47]
Construction of the CMX seemed to have worked just fine for the Yeast data. It took 1hour 13 minutes using 15 GPUs. However, while trying to run RMT for the yeast data I get the following error and I'm not sure how to debug.  

```bash

$ kinc run rmt --input Yeast.cmx --log Yeast-RMT.log --tstart 0.99 --tstep 0.001 --tstop 0.5 --minpace 10 --maxpace 40 --bins 60
../../src/core/ace_dataobject.cpp:473
void Ace::DataObject::read(char*, qint64) const
SYSTEM ERROR
Failed reading from data object file: Unknown error
```

**Comment by spficklin** [comment]
Never mind. I figured it out.  I misspelled the input CMX file it was 'yeast.cmx' with a lower-case 'y', but in the command-line above I gave it a capital 'Y'.  So, we just need a bit better error message if the file doesn't exist.

**Comment by bentsherman** [comment]
I'm surprised you don't get a more specific error message. Anyway, this is an error with ACE not KINC so I'm closing it here and you can bring this up in the ACE issues if you want.
