### ISSUE TITLE
Wrong input args for KINC cause MPI to hang.

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#48]
I reported this verbally to @4ctrl-alt-del but I thought I'd add it here for the record.   When running KINC v3 on Kamiak for the first time I requested 4 nodes with 4 GPUs and used the following submission script:

```bash
#!/bin/sh
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=4
#SBATCH --gres=gpu:tesla:4
#SBATCH --time=12:00:00    
#SBATCH --job-name=SC_similarity
#SBATCH --output=logs/02-SC_similarity.log
#SBATCH --mail-type=ALL

module load gcc/6.1.0 MPI/openmpi/3.0.0 cuda/9.1.85 qt/5.10.1 ACE/dev KINC/3.2.1

srun -v --mpi=pmi2 -l kinc run similarity --input "Yeast.emx" --clus "Yeast.ccm" --corr "Yeast.cmx" --clusmethod "gmm" --corrmethod "spearman" --minexpr -inf --minsamp 15 --minclus 1 --maxclus 5 --crit "ICL" --preout TRUE --postout TRUE --mincorr 0.5 --maxcorr 1 --ksize 4096
```
The job launched just fine, but I observed the following incorrect behavior:
1)  The processes on 3 of the 4 nodes properly bound to the GPUs, but they were using 0% of the GPU.  Thus I had 12 threads assigned to 12 GPUs but there were doing nothing not even on the CPU.
2)  The processes on the master node (where the MPI master was running) were not bound to the GPU and one of the processors was periodically busy.  An 'strace' showed it seemed to just be looping and sleeping.

It turns out the problem was caused by me providing old arguments and not using the new updated arguments. When I changed the arguments to the following then it worked just fine and finished in 1hr 13 mins:
```bash
srun -v --mpi=pmi2 -l kinc run similarity --input Yeast.emx --ccm yeast.ccm --cmx yeast.cmx --clusmethod gmm --corrmethod spearman -minexpr -inf --minsamp 15 --minclus 1 --maxclus 5 --crit ICL --preout TRUE --postout TRUE --mincorr 0.5 --maxcorr 1 --ksize 4096
```
So, KINC or ACE needs to handle the situation gracefully when bad, unknown or incorrect arguments are provided.

**Comment by bentsherman** [comment]
Running some tests on my side I can confirm that the single run exits properly with error message when given bad arguments but the MPI run does not. The MPI run doesn't even print an error message. I think this is mostly like an ACE issue. Error handling in MPI can be complicated because all MPI processes have to exit or else `mpirun` / `srun` will hang. But I still don't know why an error message isn't printed, ACE should be catching the exception thrown by KINC...

**Comment by spficklin** [comment]
As this seems to be an ACE issue I'm closing this here.
