### ISSUE TITLE
GSL error with RMT on yeast data

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#49]
When running RMT on the yeast data I'm getting the following error:

```bash
threshold: 0.99
prune matrix: 5246
eigenvalues: 5246
unique eigenvalues: 2560
gsl: interp.c:83: ERROR: x values must be monotonically increasing
```
Here's my command-line:

```bash
kinc run rmt --input yeast.cmx --log yeast-RMT.log --tstart 0.99 --tstep 0.001 --tstop 0.5 --minpace 10 --maxpace 40 --bins 60
```

**Comment by bentsherman** [comment]
Hmm, it looks like @4ctrl-alt-del reverted some of the RMT code when he went through everything. Tell him he needs to test his code more often! Hehe but anyway should be fixed now.

**Comment by spficklin** [comment]
Thanks @bentsherman!  Just to confirm, to get this fix I need to use the develop branch or the mater branch?

**Comment by bentsherman** [comment]
Use the develop branch, master is only updated for version releases.
