### ISSUE TITLE
OpenCL error OUT_OF_RESOURCES in similarity with --clusmethod=gmm

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#51]
While testing on Palmetto I get an `OUT_OF_RESOURCES` OpenCL error when I run similarity with GMMs enabled. It happens consistently on a K40 GPU; it seems to happen only sometimes on P100 GPUs, particularly if I try to do multi-GPU. It does not seem to happen on my local machine (GTX 1080Ti) which is frustrating. This problem is currently keeping me from being able to do multi-GPU tests.

This OpenCL error typically occurs when the GPU runs out of memory or something akin to a segfault happens on the GPU. Since we're not anywhere near the global memory limit I'm guessing it's the latter, so I'm going to study the GMM kernel for potential bugs. I'll update this issue when I find anything.

**Comment by spficklin** [comment]
Hi @bentsherman. I am able to run on 15 GPUs (K80s) at once here on Kamiak.  But half-way through the GPUs stop and KINC hangs waiting.  @4ctrl-alt-del is working on some debugging code to help us debug this.  I'm wondering if there's a similar issue going on.

**Comment by bentsherman** [comment]
I kind of hope they are related. But on Palmetto KINC crashes almost immediately and it gives an OpenCL error. It sounds like your error is silent and definitely not immediate. But I think Josh's debugging tools with help my case either way.

**Comment by spficklin** [comment]
I get segfaults on Kamiak immediately if I have logging turned off and I try to use MPI + GPUs.  If I turn on logging then it runs, but with the current version I'm forced to connect via telnet to each job before it gets going.  @4ctrl-alt-del is working on fixing that too.

edit:  Here's how I turn on and off logging prior to running my job.
```
kinc settings set logging off
```

```
kinc settings set logging on
```

**Comment by bentsherman** [comment]
I see, I'll have to try that then because I've been keeping logging off.

**Comment by bentsherman** [comment]
So far I've found that the bug also occurs with logging enabled. Also, it does not occur if `--maxclus` is less than 5 -- at least, it doesn't crash immediately. With `--maxclus=5` it crashes within the first few work blocks.

UPDATE: It also seems to crash for 3 and 4, it just takes longer.

**Comment by bentsherman** [comment]
I've tracked the source of the segfault to this code segment in `gmm.cl`:
```
      for (int i = 0; i < N; ++i)
      {
         // compute xm = (x_i - mu_k)
         Vector2 xm = X[i];
         vectorSubtract(&xm, mu);

         // compute Sigma_ki = gamma_ki * (x_i - mu_k) (x_i - mu_k)^T
         Matrix2x2 outerProduct;
         matrixOuterProduct(&xm, &xm, &outerProduct);

         matrixAddScaled(sigma, gmm->_loggamma[k * N + i], &outerProduct);
      }
```

I can't really zoom in much more than this. I also don't see anything wrong with the code, yet. It's almost identical to the serial code, and the serial code does not have any issues. It's also tricky because disabling this code also causes the algorithm to stop after a few iterations so I'm not sure if maybe this bug is occurring after a certain number of iterations. Still investigating.

**Comment by bentsherman** [comment]
I thought I had it -- I discovered that the `Component` struct is actually larger in kernel code than in host code, it was 64 bytes as opposed to 48 bytes. That would mean that the host code wasn't allocating enough memory for the device buffer for the components, so I fixed that. But I'm still getting the same OpenCL error. Still investigating...

**Comment by bentsherman** [comment]
I think the bug was that GMM was checking `fabs(det)` instead of `det`, which is what the CPU version does. I can't remember why I changed that but it seems to have fixed my problem on Palmetto.

On a related note, I still get `OUT_OF_RESOURCES` on K40 GPUs, which I think might be because the device is actually out of resources. I don't have this problem on newer GPUs. To remedy this I'm going to change the "kernel size" parameter to "global work size" and "local work size" so that the user can control both parameters, but can leave a 0 in local work size to tell KINC to use the maximum. I think that using the maximum all the time is causing older devices to fail.
