### ISSUE TITLE
Do we need the transform setting in ExpressionMatrix?

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#52]
After familiarizing myself with the normalization steps that a GEM undergoes between GEMmaker and KINC, I've made the following observations:
1. We always use log2 as far as I know
2. The log2 transform is typically followed by outlier removal (KS-test) and quantile normalization

So I don't really see the use of having this transform option for the expression matrix, because it's probably already going to be log2 normalized, if not also normalized in other ways. We could try to incorporate these other normalization steps into KINC, but right now I think it makes more sense to keep them separate (and others in the Feltus lab are already doing this with the GEMprep repo).

Was there some other use case for this feature @spficklin @4ctrl-alt-del ?

**Comment by spficklin** [comment]
@bentsherman I don't quite follow what you're getting at.   Can you clarify this sentence:

>So I don't really see the use of having this transform option for the expression matrix, because it's probably already going to be log2 normalized

What "transform option" are you referring to?  log2 transformation?

**Comment by bentsherman** [comment]
Yes we have an option to transform an expression matrix when you import it from the text file, you can do log2, log10, or natural log. "Transform" and "normalize" are the same here I guess.

But what we usually call "quantile normalization" is really three things in sequence: log2 normalization, outlier removal with KS-test, and the actual quantile normalization. So I don't see the point of having this normalization option by itself in KINC.

**Comment by spficklin** [comment]
Oh, I see what you mean.  All of that happens before KINC is ever used.  Yes, it would make sense to have an intermediate step between GEMmaker and KINC that can do all of that and we could take out the log2 transform from KINC.  The idea for including it was to help folks avoid a quick import into R to do the log2 transform as that will **always** need to be done.  Normalization and/or the exact type of normalization done many not be needed.

**Comment by bentsherman** [comment]
Okay. Transform setting was removed.
