### ISSUE TITLE
GUI should launch from dir that it was run in

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/KINC#55]
The first time I run KINC3's GUI from the command line in a dir, and then try to search for a file with the GUI, it will start from that directory. 

The second time I run it, running the GUI from a different dir, is when I get a minor problem. KINC's GUI will start searches from the original directory, not the one that I ran it from. 

This is a minor issue, but it would be nice to fix.

Example:
Ran the command from the apple directory:
![image](https://user-images.githubusercontent.com/35115540/48516063-4ee01400-e817-11e8-98d3-982bf4ef12e3.png)
But sense I had previously ran it in the Pear directory, the GUI goes to the first directory(Pear) when searching for file instead of the dir I ran from (Apple):
![untitled](https://user-images.githubusercontent.com/35115540/48516287-d9c10e80-e817-11e8-8368-909e129ba9ce.png)

**Comment by 4ctrl-alt-del** [comment]
I have tried to replicate this and have so far failed. I run qkinc in my home directory and select open and it starts in my home directory. I close qkinc, cd to a projects directory, and then run qkinc. When I open the file selection dialog again it now starts in the projects directory for me.

**Comment by spficklin** [comment]
I can confirm that when running qkinc on an idev session on Kamiak that it uses the last directory you ran it in rather than the current.  Just tested it now.

**Comment by bentsherman** [comment]
At the very least I think this issue is ACE-related. It looks like you can get the working directory with `QDir::currentPath()`, so we might be able to provide uniform behavior that way. Just keep in mind that this feature seems to be highly dependent on the OS so it might not be easy to make ACE behave "correctly" in every environment. Just my thoughts.

**Comment by 4ctrl-alt-del** [comment]
Just pushed a commit changing the file dialog behavior to explicitly set its working directory to the current path. This is a commit to ACE, NOT KINC, the commit is f08f01c7f7f97d9f66eeaa25b331c6dd63524a38 on the develop branch of ACE. Let me know if this changes anything.

**Comment by spficklin** [comment]
I can confirm this is now fixed on Kamiak.   As @bentsherman pointed out we may still have issues on other platforms but it seems to behave the way we want on ours.  So I'm closing.  Thanks for the fix @4ctrl-alt-del
