### ISSUE TITLE
Can not type after a "." in the "Execute Extract Network" for the KINC GUI

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/KINC#56]
I am running the GUI from Kamiak using X11 forwarding. It runs pretty well ( a little sluggish, to be expected), with one major problem. If I try to change the "Minimum Correlation" or "Maximum Correlation" value in the "Execute Extract Network" I can not type anything after I type a period ("."). This is an issue, as I either have to leave it as default (0.85 and 1) or run as 0 or 1.

I can type the period, just nothing after it. This appears to be an issue with how the GUI is perceiving what a valid number is. 

![image](https://user-images.githubusercontent.com/35115540/48515780-8a2e1300-e816-11e8-815d-407ffa49729f.png)

**Comment by spficklin** [comment]
I'm having a similar issue with changing the minimum correlation except I'm not able to edit the value at all, even after re-closing and restarting qkinc.

Alternatively, @JohnHadish you should be able to set the value you want using the command-line version.

**Comment by bentsherman** [comment]
So this is an issue with specifying the maximum number of decimals for the form input, which KINC was setting to 0 which is why you can't type any numbers after the point. I think we're going to update ACE to provide a non-zero default if the application (like KINC) doesn't specify the maximum number of decimals.

**Comment by 4ctrl-alt-del** [comment]
I just pushed an update to this on ACE to the develop branch. Please let me know if this fixes the issue. The default number of decimals value is now 1000 IF a null qt variant is returned in the appropriate analytic interface.

**Comment by spficklin** [comment]
@4ctrl-alt-del can you confirm you made changes on the 'develop' branch?  I'm going to recompile it on Kamiak.

**Comment by spficklin** [comment]
Oh... duh. I just reread your post. You said 'develop' branch.

**Comment by 4ctrl-alt-del** [comment]
Yes, on develop, commit 93f19660ef5de5b04f4c19a8a3ba210b8a155bc7.

**Comment by spficklin** [comment]
After recompiling @JohnHadish am I am now able to edit the min and max correlation fields and change them using qkinc on Kamiak. Can you confirm?

**Comment by 4ctrl-alt-del** [comment]
@JohnHadish has this been resolved for you?

**Comment by bentsherman** [comment]
This works for me, closing.
