### ISSUE TITLE
GMM = incorrect correlation values

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#57]
There seems to be a problem with KINC when using GMMs as it does not output the correct correlation values.   For example, I have run a network using GMMs + spearman and then I extract the network file.   The network file provided this result:

```
Source  Target  sc      Interaction     Cluster Num_Clusters    Cluster_Samples Missing_Samples Cluster_Outliers        Pair_Outliers   Too_Low Samples
gene176 gene68  -0.880952       co      0       1       61      0       0       0       0       1111111111111111111111111111111111111111111111111111111111111
```
When I manually run spearman correlation on those two genes I get a value of `-0.1409`.   Here's the plot of those two genes:

![image](https://user-images.githubusercontent.com/1719352/48655132-4da21900-e9c8-11e8-9ff1-ea50a2dfe49d.png)

I can provide a test dataset with these exact data for testing if needed.

**Comment by spficklin** [comment]
Oh, and here's how I ran it:

Build EMX
```
kinc run import-emx  \
  --input GEM.FPKM.log2.txt \
  --output GEM.FPKM.log2.emx \
  --nan "NA" \
  --samples 0
```

Run similarity
```
kinc run similarity \
    --input GEM.FPKM.log2.emx \
    --ccm GEM.FPKM.log2.ccm \
    --cmx GEM.FPKM.log2.cmx \
    --clusmethod gmm \
    --corrmethod spearman \
    --minexpr \
    -inf \
    --minsamp 25 \
    --minclus 1 \
    --maxclus 5 \
    --crit ICL \
    --preout TRUE \
    --postout TRUE \
    --mincorr 0.5 \
    --maxcorr 1 \
    --bsize 32768 \
    --gsize 4096 \
    --lsize 32
```
Extract network
```
threshold="0.80"
kinc run extract \
  --emx "GEM.FPKM.log2.emx" \
  --ccm "GEM.FPKM.log2.ccm" \
  --cmx "GEM.FPKM.log2.cmx" \
  --text "GEM.FPKM.log2.${threshold}.coexp.txt" \
  --graphml "GEM.FPKM.log2.${threshold}.coexp.gml" \
  --mincorr $threshold \
  --maxcorr 1
```

**Comment by spficklin** [comment]
I should also note... when we don't use GMMs on a small test set the correlation values seemed okay, so it seems the problem occurs only when GMMs are used.

**Comment by 4ctrl-alt-del** [comment]
I have been looking through the KINC code and have not found anything obvious yet. I still am not comfortable enough with Ben's code to start hacking it to force a certain condition but I think it will probably come to that. 

Where did you run those commands? I cannot find GEM.FPKM.log2.emx

**Comment by spficklin** [comment]
Oh, I obfuscated the names of those files. I'll send you some sample files you can test with.

**Comment by 4ctrl-alt-del** [comment]
@spficklin posted the raw expression data for this on #ace-kinc on sysgen slack for reference @bentsherman

**Comment by bentsherman** [comment]
I will look into this issue promptly.

**Comment by bentsherman** [comment]
It looks like CPU and GPU are consistently wrong at least. Have you tested with Pearson? I'd wonder if Pearson is also incorrect.

**Comment by spficklin** [comment]
When I ran with CPU without GMM it ran fine and correlation values seemed correct.  I don't recall if I ran without GPUs and with CPU.  Both times I ran Spearman.

**Comment by bentsherman** [comment]
There's a gene whose name is "." between gene73 and gene74, what's up with that?

**Comment by bentsherman** [comment]
After a harrowing debugging experience, I think I've resolved the discrepancy that you found. And as a bonus, the GMM code is actually quite simpler now because I discovered that one of the update equations was wrong. So now GMM should be slightly faster, it should be finding fewer clusters on average, and it should match what you find if you plot the scatter plot manually.

I haven't really documented them yet, but there is also a `visualize.py` script which you can use to generate scatter plots from an extracted network. There's also `similarity.py` which I use to verify the KINC code.

**Comment by spficklin** [comment]
Thanks @bentsherman ,  that seems to have done the trick!  I'll do some more testing to make sure I don't see any other anomalies.

**Comment by bentsherman** [comment]
@spficklin As you're testing I wanted to point out some helpful scripts that I've made:
- `run-all.sh`, `run-all-py.sh`: Shell scripts which give a basic framework for running a KINC workflow in ACE/KINC and the KINC python scripts, respectively. You can use these scripts to produce a small matrix with KINC and KINC-py and compare the output files
- `validate.py`: Compare CMX files (in plaintext form) between KINC and KINC-py runs. It's still pretty primitive but it can give you some rough numbers.
- `visualize.py`: Generate plots for a netfile, includes density and scatter plots. Pretty much a mirror of the KINC.R plotting functionality.

Eventually I'll add documentation for these scripts but feel free to try them out any way you like.

**Comment by spficklin** [comment]
@4ctrl-alt-del Thanks for looking into this.  It does appear that a recompiling of both ACE and KINC solved the problem.  But I'm a bit baffled by that because I remember checking if there were any updates to ACE between the time that I made this issue and when Ben said he fixed it and I remember there were none.  

Anyway, it seems to be fine now.  Thanks.

@bentsherman thanks for pointing out the scripts! I'll check them out.

**Comment by spficklin** [comment]
Oops, I commented to @4ctrl-alt-del on the wrong issue. I'll copy my comment there.  But I think this issue is resolved for now so I'll leave it closed.
