### ISSUE TITLE
Problem using Spearman with existing cmx file

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#6]
I tried re-running a Spearman analytic after I had prematurely killed KINC in a previous run.   Repeating the same Spearman command led to this error:

ACE Exception Caught!
What: AccelCompEng::NVMemory::Node::NullPtr
Location: void AccelCompEng::NVMemory::Node::read(int64_t):378

removing the output .cmx file that was there from the previous run resolved the problem.

**Comment by 4ctrl-alt-del** [comment]
I cannot replicate this problem. I assume it was caused by attempting to read a corrupt file however.
