### ISSUE TITLE
Confusing extract analytic dialogue

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#60]
With the most current development version of KINC the extract analytic looks like this:
![screenshot from 2018-11-29 09-47-32](https://user-images.githubusercontent.com/1719352/49241227-136b4b00-f3bc-11e8-8148-8b20a7b696ef.png)

I think the element labeled 'GraphML File' should just be labeled 'Output File'?

**Comment by bentsherman** [comment]
Whoops, done.
