### ISSUE TITLE
Persistent Settings

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#61]
In regards to issue #59 we need to make sure when we write up our usage documentation guide to describe that settings changes are persistent.    This way folks won't get confused like I did and wonder why things aren't behaving as expected.

I knew there were global persistent settings (such as debug logging) but I did not realize that the default OpenCL device was a persistent setting.  So, when I changed it in `qkinc` to test correlation values using GPUs vs non GPUs it didn't dawn on me that that change lasted beyond my qkinc session.

**Comment by 4ctrl-alt-del** [comment]
This belongs in ACE where I created the issue here: https://github.com/SystemsGenetics/ACE/issues/74

Closing this one.

**Comment by spficklin** [comment]
I think this belongs here as I'm referring to KINC User documentation.  The documentation that walks a user through how to use KINC.

**Comment by bentsherman** [comment]
Added to documentation.
