### ISSUE TITLE
Power-law thresholding analytic

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#63]
I implemented power-law thresholding a while back, it's similar to RMT except it creates an adjacency matrix on every iteration instead of a correlation matrix, and it tries to measure how scale-free the resulting network is by comparing the degree distribution to a power-law distribution. The Pearson correlation of the log-log degree distribution is used as the measure -- the higher the correlation, the more scale-free the network.

The only remaining question is knowing when to stop. I think we'll need to take a network for which we already have a reasonable threshold, observe how the scale-free measure changes as a function of the threshold, and maybe from that we can come up with a stopping criterion. Or if there is another software package that does something like this, we could refer to their code. If we can get this to work then we'll have another viable thresholding method.

**Comment by spficklin** [comment]
So is the test for when the adjacency matrix ceases to look scale free?

**Comment by bentsherman** [comment]
Yes I guess that's what we would expect to happen, since lower thresholds would introduce a lot of noise which would lower the scale-free metric. But I think we'll need to take a few networks and study how the scale-free metric changes as a function of threshold. Like does the metric always decrease at some point? And what should the cutoff be? I think we'll need a similar analysis as in your original RMT paper.

**Comment by spficklin** [comment]
Networks should be scale free but they must also be modular and heirarchical.  It is possible to have a network be scale-free and not the others.  So, I'm not sure that just a scale-free test would be enough.

**Comment by bentsherman** [comment]
Are there separate tests for those things? I'm only somewhat familiar with but I thought that scale-free networks would also be hierarchical because of the power-law distribution.

**Comment by spficklin** [comment]
I don't know of any tests for those.  There may be some.  It is possible though to have a scale free network and it not be hierarchical or modular.  This paper shows it nicely in box 2:  https://www.nature.com/articles/nrg1272

**Comment by bentsherman** [comment]
Finally took a look at this article... also spoke to Feltus and I understand that you're referring to the clustering coefficient. And it looks like this very same paper provides a hierarchical test -- basically the clustering coefficient should also follow a power-law with respect to degree.  We could add this test as an additional option to the power-law analytic, do you think that would be suitable?

**Comment by spficklin** [comment]
Yes, I think it would definitely be worth exploring.

**Comment by spficklin** [comment]
@bentsherman  I think we're agreed we can add this if there's time.  But I don't see that we need to keep issues open too long.   I'm going to close this out and we can add this TODO item to another document of enhancements we want to do.  But please reopen if you think it needs to stay in the queue.
