### ISSUE TITLE
Compare GMM and VB-GMM

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#65]
A while back I stumbled upon the variational Bayesian GMM, which is parameterized a bit differently from a regular GMM. Instead of the number of clusters, you specify a maximum number of clusters and a "concentration prior", which essentially controls how complex the model becomes. The model will then use as many clusters as it sees fit. This means that a single VB-GMM could replace 5 GMMs for a gene pair, and as long as the VB-GMM isn't too much slower, we'd probably get some speedup.

I created a script a while back called `test-vbgmm.py` so that I could compare the two. There are still some details that need to be worked out before it's worth implementing:
- What should the weight concentration prior be? If we can't pick a single value that works in a broad sense then we're no better off than with GMMs.
- The VB-GMM technically still uses all of the clusters given to it, but it assigns a weight to each cluster, and if it didn't "use" a cluster then the cluster just has a really low weight. So we would need a reasonable weight threshold as well for knowing when to exclude a cluster.

If we can find reasonable constants for these two things then it might be worth implementing VB-GMM later on.

**Comment by spficklin** [comment]
Oh, this is interesting. Do you have a document to link to to learn more?

**Comment by bentsherman** [comment]
https://scikit-learn.org/stable/modules/mixture.html#bgmm

**Comment by spficklin** [comment]
Closing this out because it's been in the queue a long time and will get done when/if we can find the time.  So, to keep issues from languishing in the queue I've tagged with 'For the Future" and "enhancement"
