### ISSUE TITLE
Support "R-ready" GEM files in import-emx

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#68]
I've noticed that a lot of people put something like "RowID" in the header row because R requires this format for data tables. So I think it would be good to support this format somehow. Probably the cleanest way would be to just add a checkbox for "Header row contains "Row ID" element" or something like that. If the user has a GEM with this extra element, they check it and KINC will throw out this element from the samples list.

Same thing for export-emx, allow the user to specify whether or not to include this header element.

**Comment by spficklin** [comment]
Hi @bentsherman, we've not had to use a RowID to read in network tables. Here's how KINC.R reads it in:

https://github.com/SystemsGenetics/KINC.R/blob/61355dd7da4ea5ba0a92b471e81cb9529602aef6/R/base.R#L22-L23

Is there a particular application you're thinking of that might require a RowID header?

**Comment by bentsherman** [comment]
@spficklin I think Ihat only works without the RowID because you're providing the row names and column names beforehand. With the GEM files the row and column names need to be read in dynamically, and if you don't provide RowID then the column names get shifted over one. At least that's what we've observed on our end.

**Comment by spficklin** [comment]
We can check and see, but I don't recall ever having a problem loading network files in R without the RowID. In fact that's why we designed KINC to not have that first column name because R read.table function seems to like it that way by default.

**Comment by spficklin** [comment]
@bentsherman does this still require some conversation?  We've been importing and exporting files between KINC and R with no problems. But I may not be understanding what  you're after.

**Comment by bentsherman** [comment]
@spficklin If you all haven't had any trouble then I will put this issue to rest. I'd rather not bother with it anyway.
