### ISSUE TITLE
Power analysis filtering

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#69]
So after GMMs run it may be useful to perform a power analysis test on each cluster.  It would require that we add an alpha and beta parameter setting to the KINC GMM analytic.  For example, the `pwr.r.test` function in R does this type of test for Pearsons/Spearman correlation.   Essentially, if we don't have enough samples in the cluster to ensure an expected level of significance and power then we just don't do correlation analysis on the cluster.   it would help ensure that false positive edges due to improper application of correlation aren't included in the network.

I added this issue on KINC.R as well but then thought it might be easy enough to just implement in KINC.

https://github.com/SystemsGenetics/KINC.R/issues/7

**Comment by bentsherman** [comment]
On a related note, it looks like the code in its current state does a basic check on the sample size for each cluster. So if the cluster size falls below the min-samples parameter then it will be skipped.

**Comment by spficklin** [comment]
Yes, I think the power analysis filter would be a better way to do that.   Instead users could set an alpha and beta indicating how much false negatives/positives they are willing to tolerate in the network.  We could then get rid of that check which it turns out we often forget to set it and wind up redoing networks more than once.  I think the alpha/beta settings would be more intuitive.
