### ISSUE TITLE
Read the Docs for KINC

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#71]
We should add a nice Read the Docs instruction set for how to use KINC with pages for 
1. A description of how KINC is FAIR
2. Installation instructions on stand-alone machine
3. Docker usage instructions (we need a Docker image)
4. An example run-through for how to construct a network:
    a.  traditional, no GMM
    b.  GMM
5. pages for each analytic so that folks know what they are for.  
6. pages for each data class so folks understand them

**Comment by bentsherman** [comment]
Added to documentation.
