### ISSUE TITLE
Consistent BLAS libraries

### ISSUE THREAD

**Issue by 4ctrl-alt-del** [SystemsGenetics/KINC#72]
@bentsherman Stephen wants us to make sure we are using the same BLAS library implementation when compiling KINC so we do not have to change any linker flags. Obviously you are not using openblas so what should I be using on kamiak so I do not have to change any linker flags?

**Comment by bentsherman** [comment]
Actually I am using openblas, I'm just using the "generic" BLAS flags to link to it. Could you send me your current list of linker flags that works on Kamiak? If I can use the same flags on Palmetto and my lab machine then we can just update KINC with your flags. I assume you're just using `-lopenblas`.

**Comment by 4ctrl-alt-del** [comment]
Correct.
````
$ git diff KINC.pri
diff --git a/src/KINC.pri b/src/KINC.pri
index 65f1e28..3ba4a54 100644
--- a/src/KINC.pri
+++ b/src/KINC.pri
@@ -28,7 +28,7 @@ isEmpty(MPICXX) { MPICXX = "yes" }
 LIBS += \
     -L$${PWD}/../build/libs -lkinccore \
     -lacecore \
-    -lgsl -lgslcblas -llapack -llapacke \
+    -lgsl -lgslcblas -lopenblas \
     -lOpenCL -lmpi
 equals(MPICXX,"yes") { LIBS += -lmpi_cxx }
 
$
````

**Comment by spficklin** [comment]
We have openblas installed on Kamiak so that works good for us.

**Comment by bentsherman** [comment]
So I also had to use `-llapacke` on my local machine, on Palmetto it worked with and without that flag. So like this:
```
-lgsl -lgslcblas -llapacke -lopenblas
```

Can you still build KINC successfully on Kamiak with this extra flag?

**Comment by 4ctrl-alt-del** [comment]
No it does not work.
````
$ cat ../src/KINC.pri
...
# External libraries
LIBS += \
    -L$${PWD}/../build/libs -lkinccore \
    -lacecore \
    -lgsl -lgslcblas -llapacke -lopenblas \
    -lOpenCL -lmpi
...
$ make
cd core/ && ( test -e Makefile || /data/ficklin/software/qt-5.10.1/5.10.1/gcc_64/bin/qmake -o Makefile /home/josh.burns/projects/KINC/src/core/core.pro PREFIX=/home/josh.burns/software MPICXX=no ) && make -f Makefile 
make[1]: Entering directory `/home/josh.burns/projects/KINC/build/core'
make[1]: Nothing to be done for `first'.
make[1]: Leaving directory `/home/josh.burns/projects/KINC/build/core'
cd cli/ && ( test -e Makefile || /data/ficklin/software/qt-5.10.1/5.10.1/gcc_64/bin/qmake -o Makefile /home/josh.burns/projects/KINC/src/cli/cli.pro PREFIX=/home/josh.burns/software MPICXX=no ) && make -f Makefile 
make[1]: Entering directory `/home/josh.burns/projects/KINC/build/cli'
g++ -Wl,-O1 -Wl,-rpath,/data/ficklin/software/qt-5.10.1/5.10.1/gcc_64/lib -o kinc main.o qrc_opencl.o   -L/home/josh.burns/projects/KINC/src/../build/libs -lkinccore -lacecore -lgsl -lgslcblas -llapacke -lopenblas -lOpenCL -lmpi -laceconsole -L/data/ficklin/software/qt-5.10.1/5.10.1/gcc_64/lib -lQt5Gui -lQt5Core -lGL -lpthread 
/usr/bin/ld: cannot find -llapacke
/usr/bin/ld: cannot find -lopenblas
collect2: error: ld returned 1 exit status
make[1]: *** [kinc] Error 1
make[1]: Leaving directory `/home/josh.burns/projects/KINC/build/cli'
make: *** [sub-cli-make_first] Error 2
$
````

**Comment by spficklin** [comment]
Ben we are using openblas 0.3.0 and it seems to work without that `-llapacke` flag. What version are you using?

**Comment by bentsherman** [comment]
@4ctrl-alt-del it says your build didn't find `-lopenblas` either, did you have the module loaded? It would be weird if that error was somehow caused by adding the lapacke flag.

@spficklin I'm using openblas 0.2.18 which is the default version on Ubuntu 16.04. Currently trying to see if I can make it work on my lab machine without the extra flag.

**Comment by 4ctrl-alt-del** [comment]
My bad I forgot to load openblas. It still does not work though and complains about not finding lapacke.

**Comment by bentsherman** [comment]
After comparing the openblas installations on Palmetto and Ubuntu, I found that the openblas library on Palmetto is built with LAPACKE while the library on Ubuntu is not. That's why I have to link to LAPACKE on Ubuntu. Palmetto has openblas 0.2.20, so I don't think it's a version difference but rather the build options that were used when openblas is built.

So probably the easiest way to resolve this difference is to add a flag to `KINC.pri` for whether to link to LAPACKE. There's already an option like this for MPI_CXX so I can add this quickly.

**Comment by bentsherman** [comment]
And for future reference, here's how you can inspect a library to see all of the functions that it contains:
```
# for a shared library
nm -D libopenblas.so

# for a static library
nm libopenblas.a
```

**Comment by bentsherman** [comment]
@4ctrl-alt-del Just pushed my update so let me know if it works for you on Kamiak. I think you'll have to do something like `qmake ../src LINK_LAPACKE=0`.

Also note that I got rid of the develop branch since we have versioned releases so everything is on the master branch now.

**Comment by bentsherman** [comment]
Closing as there no longer seems to be an issue here.
