### ISSUE TITLE
Usage Instructions for KINC on Palmetto update

### ISSUE THREAD

**Issue by mrbende** [SystemsGenetics/KINC#77]
The final step for palmetto usage instructions, submitting a job using qsub, should be updated from 

'qsub -v GEM=EDS1014_GEM.txt,OUTNAME=EDS1014 run_KINc.sh'

to...

'qsub -v GEM="EDS1014_GEM.txt",OUTNAME="EDS1014" run_KINC.sh'

**Comment by bentsherman** [comment]
Done!
