### ISSUE TITLE
Memory usage when processing a large GEM with many MPI ranks

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#79]
We've noticed on Palmetto that large KINC jobs tend to run out of memory. That is, when we run similarity with many MPI ranks (100-1000) on a large GEM (like GTEX), the job gets killed due to exceeding it's memory allocation. I think I've tried as much as 32GB per rank. It could be a single node that does this, so my guess is that the master node gets flooded with too many result blocks.

It would be nice if we could fix this but the first step is really just to profile the memory usage of similarity when using MPI. How much does the master use? How much does each worker use? How does memory usage scale with the number of nodes and with the input GEM size? I should be able to collect this data using the nextflow pipeline.

If we determine that memory usage just scales poorly with MPI, we may be able to optimze ACE/KINC to reduce it. At the end of the day, we can always fall back on using the chunk run.

**Comment by spficklin** [comment]
This issue is over a year old.  Is this still a problem?

**Comment by bentsherman** [comment]
Hmm this seems to be some thoughts I wrote down for myself. I'd like to study the memory usage of large-scale KINC runs at some point for my thesis work, but that's really just for me so I'll close this one out.
