### ISSUE TITLE
checkpointing

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#81]
This may be a question for ACE, but is it possible to checkpoint an analytic.  For example, if an analytic is interrupted but has run for a long time, can we make it pick up where it left off rather than start everything over?

**Comment by bentsherman** [comment]
Right now ACE/KINC doesn't really have a way to recover output files that got interrupted, and I can't really speak to how difficult it would be to implement a way of recovery.

However I have thought about this issue before and the best solution I came up with is to use the KINC-nf workflow in "chunk" mode, so nextflow will get through similarity by submitting many small jobs as "chunks". So basically the way you run it on OSG, but using nextflow on whatever system. That way if the workflow gets interrupted you only lose the chunks that were incomplete, and you can still make full use of you're HPC cluster.

**Comment by 4ctrl-alt-del** [comment]
This would have to be implemented in ACE. As Ben described it is kind of de facto implemented if you use chunk run. It would take considerable effort to add that kind of support running in MPI mode.

**Comment by bentsherman** [comment]
Closing since nextflow can be used for checkpointing.
