### ISSUE TITLE
Integrate features from KINC.R

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#82]
Quoting @spficklin from a previous thread:

> Although we have a problem with RMT thresholding for condition-specific networks. Right now we are bypassing the KINC threshold step and using KINC.R for network creation after KINC similarity is run. For example, we export a network at some arbitrarily low threshold (e.g. 0.70). Then we import that network into KINC.R along with an annotation matrix file that maps experimental conditions to each sample. KINC.R assign a p-value to each edge (i.e. GMM cluster) for a given experimental condition (e.g. heat exposure, control, inoculated, etc.). The user can then specify a set of p-value filters to get a list of edges that are condition-specific.

> However, this approach is clunky to do and it requires the user to leave KINC to work with KINC.R. If we could do this filtering with KINC it would save a lot of time and we could go back to using RMT thresholding too. To make this happen with KINC, we would need to make a new data class for storing p-values for conditions and a new analytic for calculating those p-values. Then we would need to adjust the RMT analytic to use the new p-values data file for thresholding. User's wouldn't need KINC.R to do the conditional thresholding, which I think makes KINC even more powerful as as stand-alone tool.

**Comment by spficklin** [comment]
Note:  pulled from issue #31 
Thanks @bentsherman

**Comment by spficklin** [comment]
This is in progress and I don't think we need an open issue for this in general.
