### ISSUE TITLE
Correlation discrepancy

### ISSUE THREAD

**Issue by JordanLittle98** [SystemsGenetics/KINC#84]
I got the incorrect correlation values when running kinc compared to scatterplots I made by hand. For example, the correlation given by Kinc for the gene pair AKT2m and CCNB1gin is 0.99987894, but when I make the scatter plots by hand I get this:
![AKT2m_CCNB1gin copy](https://user-images.githubusercontent.com/32000369/55897163-fdea0700-5b8d-11e9-8988-3a8aa9861864.png)

I can provide my GEM and any other files needed

**Comment by spficklin** [comment]
Hi @JordanLittle98. a few questions
1) Can you provide the KINC command-line you used?  
2) Can you redo your plot without a fixed y-axis?  Let it scale automatically.
3) What correlation value do you get if your run just those two genes independently (e.g. in R or Python)?

**Comment by JordanLittle98** [comment]
1. I used a pbs script that does the following: 

Import expression matrix into binary
`kinc run import-emx --input 5hrs_GEM --output 5hrs.emx --nan NA`

Compute similarity matrix
`mpirun -np 100 --mca mpi_cuda_support 0 \`
`kinc run similarity \`
`--input 5hrs.emx \`
`--ccm 5hrs.ccm \`
`--cmx 5hrs.cmx \`
`--clusmethod gmm \`
`--corrmethod spearman \`
`--minclus 1 \`
`--maxclus 5`

determine correlation threshold
`kinc run rmt --input 5hrs.cmx --log 5hrs.log`

Read threshold from log file 
`THRESHOLD=$(tail -n 1 5hrs.log)`

extract network file from threshold similarity matrix
`kinc run extract --emx 5hrs.emx --ccm 5hrs.ccm --cmx 5hrs.cmx --output 5hrs-net.txt --mincorr $THRESHOLD`

2. This is scaled automatically, the CCNB1gin gene doesn't change between any of the samples 

3. When I look at the correlation of these two genes independently I get  -1.27328E-15

**Comment by JordanLittle98** [comment]
1. I used a pbs script that does the following: 

Import expression matrix into binary
`kinc run import-emx --input 5hrs_GEM --output 5hrs.emx --nan NA`

Compute similarity matrix
`mpirun -np 100 --mca mpi_cuda_support 0 \`
`kinc run similarity \`
`--input 5hrs.emx \`
`--ccm 5hrs.ccm \`
`--cmx 5hrs.cmx \`
`--clusmethod gmm \`
`--corrmethod spearman \`
`--minclus 1 \`
`--maxclus 5`

determine correlation threshold
`kinc run rmt --input 5hrs.cmx --log 5hrs.log`

Read threshold from log file 
`THRESHOLD=$(tail -n 1 5hrs.log)`

extract network file from threshold similarity matrix
`kinc run extract --emx 5hrs.emx --ccm 5hrs.ccm --cmx 5hrs.cmx --output 5hrs-net.txt --mincorr $THRESHOLD`

2. This is scaled automatically, the CCNB1gin gene doesn't change between any of the samples 

3. When I look at the correlation of these two genes independently I get  -1.27328E-15

**Comment by JordanLittle98** [comment]
1. I used a pbs script that does the following: 

Import expression matrix into binary
`kinc run import-emx --input 5hrs_GEM --output 5hrs.emx --nan NA`

Compute similarity matrix
`mpirun -np 100 --mca mpi_cuda_support 0 \`
`kinc run similarity \`
`--input 5hrs.emx \`
`--ccm 5hrs.ccm \`
`--cmx 5hrs.cmx \`
`--clusmethod gmm \`
`--corrmethod spearman \`
`--minclus 1 \`
`--maxclus 5`

determine correlation threshold
`kinc run rmt --input 5hrs.cmx --log 5hrs.log`

Read threshold from log file 
`THRESHOLD=$(tail -n 1 5hrs.log)`

extract network file from threshold similarity matrix
`kinc run extract --emx 5hrs.emx --ccm 5hrs.ccm --cmx 5hrs.cmx --output 5hrs-net.txt --mincorr $THRESHOLD`

2. This is scaled automatically, the CCNB1gin gene doesn't change between any of the samples 

3. When I look at the correlation of these two genes independently I get  -1.27328E-15

**Comment by bentsherman** [comment]
@spficklin Wanted to let you know that Jordan is working with gene expression data generated from simulations rather than real experiments, so I think some of her data has some interesting edge cases that we haven't seen before with KINC. It could be that our Spearman implementation isn't quite robust enough to handle it, compared to the R or Python implementation.

We will follow up with her in the Feltus lab and examine some more scatter plots to see if there is a broader pattern. @JordanLittle98 if you could go ahead and generate scatter plots for every edge in your network we can go through them at the next lab meeting.

**Comment by spficklin** [comment]
Hi folks. I'm just checking in on this to see if we can close it out or if there's a bug?  thanks.

**Comment by bentsherman** [comment]
I believe Jordan was able to resolve this issue by removing the genes with this strange expression pattern and it actually improved her network. I don't think this expression pattern is one that we really need to account for right now as it doesn't occur in real expression data.
