### ISSUE TITLE
mixture model data makes files too big

### ISSUE THREAD

**Issue by 4ctrl-alt-del** [SystemsGenetics/KINC#9]
mixture model data makes file sizes of insanely large size with large sample sizes(74000 genes and 2000 samples produces a 6.67 terrabyte file).

As a result need to remove mixture model data from correlation matrix.

**Comment by 4ctrl-alt-del** [comment]
Started working on this today, will take some time since correlation matrix data is used everywhere and the class itself requires a substantial refactoring to remove mode data.

**Comment by 4ctrl-alt-del** [comment]
Fixed with KINC version 3.1 correlation data is not treated as a sparse matrix.
On one test file the size went from 700MB to 100MB using a cutoff of 0.5.

**Comment by spficklin** [comment]
Great!  Thanks @4ctrl-alt-del
