### ISSUE TITLE
Concrete Unit Testing

### ISSUE THREAD

**Issue by 4ctrl-alt-del** [SystemsGenetics/KINC#96]
I think we need to integrate the very handy python scripts you made to make some concrete unit tests for KINC. By concrete I mean using validated results. An example is back when I was programming KINC on my own I had Stephen provide me with a very small expression matrix and resulting correlation matrix with the correct values.

I'm thinking we should add predetermined data sets, expression, correlation, and cluster with all the correct values. In this way we can then run unit tests with KINC that validates it by making sure what it produces is the same thing.

**Comment by spficklin** [comment]
We definitely need this!  But to keep issues from languishing in the queue. I'm closing and tagging with "enhancement" and "for the future" so we can find it later and remind ourselves it needs doing.
