### ISSUE TITLE
CH index (model selection criterion)

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#98]
Benafsh has been experimenting with a workflow based on KINC which uses the CH index to select the number of clusters for each gene pair:
```
CH index = SS_b / SS_w * (N - k) / (k - 1)
```

More infornation here: http://ethen8181.github.io/machine-learning/clustering_old/clustering/clustering.html

This might be an interesting criterion to add to the GMM step, as an alternative to BIC or ICL. We can add it easily to the python script to try it out and maybe eventually implement it in KINC.

**Comment by spficklin** [comment]
This is something worth while but is dependent on our ability to find time for it.  To keep issues from being in the queue indefinitely I'm closing out and tagging with "enhacement" and "For the future" so we can find it again later.
