### ISSUE TITLE
Mutual information

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#99]
Our view on MI has mainly been that it isn't as useful as Pearson or Spearman for finding significant correlations. However Benafsh has been experimenting with MI and she's actually able to get some interesting results with it (paper submission pending!) so I think MI might be worth considering again. I think the main thing is that MI doesn't behave the same way as conventional correlation metrics, it is less restrictive, but edges with high MI are still interesting in other ways.

I will try to add MI to the python script, but this might be a good project for an undergrad, to implement MI in KINC (same for Kendall Tau btw).

**Comment by spficklin** [comment]
My experience using MI is that while it does find similar relationships to correlation methods it sometimes includes edges that just make no sense.  Then these two papers both indicated poor performance of MI:

Song, L., Langfelder, P., & Horvath, S. (2012). Comparison of co-expression measures: Mutual information, correlation, and model based indices. BMC Bioinformatics, 13(1), 328. 

Lindlöf, A., & Lubovac, Z. (2005). Simulations of simple artificial genetic networks reveal features in the use of Relevance Networks. In Silico Biol (Gedrukt).

So, I'm interested to see what you all have found.  If you are getting good results with MI you might want to address the criticisms raised in these papers and why you all might be seeing something better.

**Comment by spficklin** [comment]
I'm just re-touching old issues.  I'm not opposed to adding in MI. If there's time for it, let's do it!  However, I don't want to leave issues open for a long time.  I think we close this out and add MI to a list of enhancements we will do in the future if time permits.  So, I'm closing, but @bentsherman if you really think this should stay in this queue, please reopen.
